// lkda-web/src/views/volume/VolumeListView.vue
<script setup lang="ts">
import { ref, reactive, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useDictStore } from '@/stores/dict'
import { useAuthStore } from '@/stores/auth'
import { VolumeApi } from '@/api/volume'
import type { ArchiveVolumeListVO } from '@/types/vo'
import ViewModeToggle from '@/components/ViewModeToggle.vue'
import { useViewMode } from '@/composables/useViewMode'

const router    = useRouter()
const dictStore = useDictStore()
const authStore = useAuthStore()

// ── 视图模式 ────────────────────────────────────────────────────
const viewMode = useViewMode('volume')

// ── 年度选项（2018 - 当前年）────────────────────────────────────
const currentYear = new Date().getFullYear()
const yearOptions = Array.from({ length: currentYear - 2017 }, (_, i) =>
  String(currentYear - i),
)

// ── 字典选项 ────────────────────────────────────────────────────
const categoryL1Options = computed(() => dictStore.getDictItems('category_l1'))
const categoryL2Options = computed(() => dictStore.getDictItems('category_l2'))

const STATUS_OPTIONS = [
  { label: '草稿',   value: 0 },
  { label: '待审核', value: 1 },
  { label: '待确认', value: 2 },
  { label: '已归档', value: 3 },
]

const STOCK_OPTIONS = [
  { label: '在库', value: 1 },
  { label: '借出', value: 0 },
]

// ── 查询参数 ────────────────────────────────────────────────────
const query = reactive({
  year:       undefined as string | undefined,
  categoryL1: undefined as string | undefined,
  categoryL2: undefined as string | undefined,
  status:     undefined as number | undefined,
  inStock:    undefined as number | undefined,
  keyword:    '',
  current:    1,
  size:       20,
})

// 一级类目变更时重置二级
watch(() => query.categoryL1, () => { query.categoryL2 = undefined })

// ── 列表数据 ────────────────────────────────────────────────────
const loading   = ref(false)
const tableData = ref<ArchiveVolumeListVO[]>([])
const total     = ref(0)

async function loadList() {
  loading.value = true
  try {
    const res = await VolumeApi.page({
      ...query,
      keyword: query.keyword || undefined,
    })
    tableData.value = res.records
    total.value     = res.total
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  query.current = 1
  loadList()
}

function handleReset() {
  query.year       = undefined
  query.categoryL1 = undefined
  query.categoryL2 = undefined
  query.status     = undefined
  query.inStock    = undefined
  query.keyword    = ''
  query.current    = 1
  loadList()
}

onMounted(async () => {
  if (!dictStore.loaded) {
    await dictStore.loadAll().catch(() => {})
  }
  loadList()
})

// ── 权限 ────────────────────────────────────────────────────────
const isAdmin = computed(() => authStore.isAdmin)

// ── 导航操作 ────────────────────────────────────────────────────
const goDetail = (row: ArchiveVolumeListVO) => router.push({
  path: `/volume/detail/${row.recordId}`,
  query: { year: row.year }
})
const goEdit   = (row: ArchiveVolumeListVO) => router.push({
  path: `/volume/edit/${row.recordId}`,
  query: { year: row.year }
})
const goBorrow = (row: ArchiveVolumeListVO) => router.push({
  path: `/borrow/apply/${encodeURIComponent(row.archiveNo)}`,
})
const goNew    = () => router.push('/volume/edit')
const goImport = () => router.push('/volume/import')

// ── 密级标签样式 ────────────────────────────────────────────────
const SECURITY_STYLE: Record<string, { bg: string; color: string }> = {
  public:       { bg: '#F0FDF4', color: '#166534' },
  internal:     { bg: '#EFF6FF', color: '#1E40AF' },
  secret:       { bg: '#FFFBEB', color: '#92400E' },
  confidential: { bg: '#FFF7ED', color: '#9A3412' },
  topsecret:    { bg: '#FFF1F2', color: '#881337' },
}
const securityStyle = (level: string) =>
  SECURITY_STYLE[level] ?? { bg: '#F1F5F9', color: '#64748B' }

// 案卷归档状态展示值（优先判断销毁待审批）
const archiveStatusValue = (row: ArchiveVolumeListVO) => {
  if (row.pendingDestroy === 1) return 10
  return row.status
}
</script>

<template>
  <div class="page-container">
    <PageHeader title="案卷目录" />

    <!-- ── 检索面板 ──────────────────────────────────────────────── -->
    <div class="search-panel">
      <div class="search-grid">
        <el-select v-model="query.year" placeholder="年度" clearable>
          <el-option v-for="y in yearOptions" :key="y" :label="y + ' 年'" :value="y" />
        </el-select>

        <el-select v-model="query.categoryL1" placeholder="一级类目" clearable>
          <el-option
            v-for="item in categoryL1Options"
            :key="item.itemValue"
            :label="item.itemLabel"
            :value="item.itemValue"
          />
        </el-select>

        <el-select
          v-model="query.categoryL2"
          placeholder="二级类目"
          clearable
          :disabled="!query.categoryL1"
        >
          <el-option
            v-for="item in categoryL2Options"
            :key="item.itemValue"
            :label="item.itemLabel"
            :value="item.itemValue"
          />
        </el-select>

        <el-select v-model="query.status" placeholder="归档状态" clearable>
          <el-option
            v-for="s in STATUS_OPTIONS"
            :key="s.value"
            :label="s.label"
            :value="s.value"
          />
        </el-select>

        <el-select v-model="query.inStock" placeholder="在库状态" clearable>
          <el-option
            v-for="s in STOCK_OPTIONS"
            :key="s.value"
            :label="s.label"
            :value="s.value"
          />
        </el-select>

        <el-input
          v-model="query.keyword"
          placeholder="案卷题名 / 档号 / 主题词"
          clearable
          prefix-icon="Search"
          @keyup.enter="handleSearch"
        />

        <div class="search-actions">
          <el-button type="primary" @click="handleSearch">
            <el-icon><Search /></el-icon>
            检索
          </el-button>
          <el-button @click="handleReset">
            <el-icon><RefreshLeft /></el-icon>
            重置
          </el-button>
        </div>
      </div>
    </div>

    <!-- ── 工具栏 ────────────────────────────────────────────────── -->
    <div class="toolbar">
      <div class="toolbar-left">
        <el-button type="primary" class="new-btn" @click="goNew">
          <el-icon><Plus /></el-icon>
          新建案卷
        </el-button>
        <el-button v-if="isAdmin" @click="goImport">
          <el-icon><Upload /></el-icon>
          批量导入
        </el-button>
        <el-button>
          <el-icon><Download /></el-icon>
          导出列表
        </el-button>
      </div>

      <ViewModeToggle v-model="viewMode" />
    </div>

    <!-- ── 表格视图 ──────────────────────────────────────────────── -->
    <el-card v-if="viewMode === 'table'" shadow="never" class="table-card">
      <el-table
        v-loading="loading"
        :data="tableData"
        row-key="recordId"
        class="archive-table"
        max-height="calc(100vh - 300px)"
      >
        <template #empty>
          <EmptyState description="暂无案卷数据，试试调整检索条件" />
        </template>

        <el-table-column prop="archiveNo" label="档号" min-width="160" show-overflow-tooltip />
        <el-table-column prop="volumeTitle" label="案卷题名" min-width="220" show-overflow-tooltip />
        <el-table-column prop="year" label="年度" width="72" align="center" />

        <el-table-column label="密级" width="90" align="center">
          <template #default="{ row }">
            <span
              class="security-tag"
              :style="securityStyle(row.securityLevel)"
            >{{ row.securityLevelLabel || row.securityLevel || '—' }}</span>
          </template>
        </el-table-column>

        <el-table-column label="保管期限" width="96" align="center">
          <template #default="{ row }">
            <span class="period-text">{{ row.retentionPeriodLabel || row.retentionPeriod || '—' }}</span>
          </template>
        </el-table-column>

        <el-table-column label="归档状态" width="100" align="center">
          <template #default="{ row }">
            <StatusTag type="archive" :value="archiveStatusValue(row)" />
          </template>
        </el-table-column>

        <el-table-column label="在库" width="76" align="center">
          <template #default="{ row }">
            <StatusTag type="stock" :value="row.inStock" />
          </template>
        </el-table-column>

        <el-table-column label="操作" width="160" fixed="right" align="center">
          <template #default="{ row }">
            <el-button link type="primary" @click="goDetail(row)">查看</el-button>
            <el-button
              v-if="row.status === 0"
              link
              type="primary"
              @click="goEdit(row)"
            >编辑</el-button>
            <el-button
              v-if="row.status === 3 && row.inStock === 1"
              link
              type="success"
              @click="goBorrow(row)"
            >借阅</el-button>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination-wrap">
        <el-pagination
          v-model:current-page="query.current"
          v-model:page-size="query.size"
          :total="total"
          :page-sizes="[20, 50]"
          layout="total, sizes, prev, pager, next"
          background
          @change="loadList"
        />
      </div>
    </el-card>

    <!-- ── 卡片视图 ──────────────────────────────────────────────── -->
    <div v-else class="card-view" v-loading="loading">
      <EmptyState
        v-if="!loading && tableData.length === 0"
        description="暂无案卷数据，试试调整检索条件"
      />

      <div class="card-grid">
        <div
          v-for="row in tableData"
          :key="row.recordId"
          class="archive-card"
          @click="goDetail(row)"
        >
          <div class="archive-card-icon-wrap">
            <el-icon class="archive-card-icon"><Folder /></el-icon>
          </div>
          <div class="archive-card-body">
            <div class="archive-card-no">{{ row.archiveNo }}</div>
            <div class="archive-card-title" :title="row.volumeTitle">
              {{ row.volumeTitle }}
            </div>
            <div class="archive-card-meta">
              <span class="meta-year">{{ row.year }} 年</span>
              <span
                class="security-tag small"
                :style="securityStyle(row.securityLevel)"
              >{{ row.securityLevelLabel || row.securityLevel || '—' }}</span>
            </div>
          </div>
          <div class="archive-card-footer">
            <StatusTag type="archive" :value="archiveStatusValue(row)" />
            <StatusTag type="stock" :value="row.inStock" />
            <el-button
              v-if="row.status === 3 && row.inStock === 1"
              link
              type="success"
              size="small"
              @click.stop="goBorrow(row)"
            >借阅</el-button>
          </div>
        </div>
      </div>

      <div v-if="tableData.length > 0" class="card-pagination">
        <el-pagination
          v-model:current-page="query.current"
          v-model:page-size="query.size"
          :total="total"
          :page-sizes="[20, 50]"
          layout="total, sizes, prev, pager, next"
          background
          @change="loadList"
        />
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.page-container {
  padding: 16px 24px 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

// ── 检索面板 ────────────────────────────────────────────────────
.search-panel {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  background: #fff;
  box-shadow: var(--shadow-card);
  padding: 20px;
}

.search-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, auto));
  gap: 12px;
  margin-bottom: 0;
  align-items: center;

  :deep(.el-select),
  :deep(.el-input) {
    width: 100%;

    .el-input__wrapper {
      border-radius: 8px;
      box-shadow: 0 0 0 1px #E2E8F0;
      transition: box-shadow 0.2s;

      &:hover   { box-shadow: 0 0 0 1px var(--theme-accent-light); }
      &.is-focus { box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 30%, transparent); }
    }
  }

  .search-actions {
    display: flex;
    gap: 10px;
    justify-self: start;
    align-self: center;
  }
}

// ── 工具栏 ────────────────────────────────────────────────────────
.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
}

.toolbar-left {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.new-btn {
  background: linear-gradient(135deg, $color-primary, $color-primary-dark);
  border: none;
  font-weight: 600;
  border-radius: var(--radius-btn);

  &:hover {
    opacity: 0.9;
  }
}

.view-toggle {
  display: flex;
  gap: 6px;

  .el-button {
    border-radius: 8px;
  }
}

// ── 表格卡片 ──────────────────────────────────────────────────────
.table-card {
  :deep(.el-card__body) {
    padding: 0;
  }
}

.archive-table {
  :deep(.el-table__header-wrapper th) {
    background: #F8FAFC;
    color: $color-text-body;
    font-weight: 600;
    font-size: 13px;
  }

  :deep(.el-table__row) {
    cursor: pointer;
    transition: background 0.15s;

    &:hover td {
      background: var(--theme-bg-soft) !important;
    }
  }
}

.security-tag {
  display: inline-flex;
  align-items: center;
  padding: 2px 8px;
  border-radius: var(--radius-tag);
  font-size: 11px;
  font-weight: 600;
  white-space: nowrap;

  &.small {
    padding: 1px 6px;
    font-size: 10px;
  }
}

.period-text {
  font-size: 12px;
  color: $color-text-body;
}

.pagination-wrap {
  display: flex;
  justify-content: flex-end;
  padding: 16px 20px;
  border-top: 1px solid #F1F5F9;
}

// ── 卡片视图 ──────────────────────────────────────────────────────
.card-view {
  min-height: 200px;
}

.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 12px;
  margin-bottom: 20px;
}

.archive-card {
  background: #fff;
  border: 1px solid #E2E8F0;
  border-radius: var(--radius-card);
  padding: 16px;
  cursor: pointer;
  transition: border-color 0.2s, box-shadow 0.2s, transform 0.2s;
  display: flex;
  flex-direction: column;
  gap: 12px;

  &:hover {
    border-color: $color-primary;
    box-shadow: 0 4px 16px color-mix(in srgb, var(--color-primary) 15%, transparent);
    transform: translateY(-2px);
  }
}

.archive-card-icon-wrap {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  background: linear-gradient(135deg, var(--theme-bg-lighter), var(--theme-border-medium));
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.archive-card-icon {
  font-size: 22px;
  color: $color-primary-dark;
}

.archive-card-body {
  flex: 1;
  min-width: 0;
}

.archive-card-no {
  font-size: 11px;
  color: #94A3B8;
  margin-bottom: 4px;
  font-family: monospace;
  letter-spacing: 0.3px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.archive-card-title {
  font-size: 14px;
  font-weight: 600;
  color: $color-text-title;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  margin-bottom: 8px;
}

.archive-card-meta {
  display: flex;
  align-items: center;
  gap: 8px;
}

.meta-year {
  font-size: 12px;
  color: $color-text-body;
}

.archive-card-footer {
  display: flex;
  gap: 6px;
  padding-top: 10px;
  border-top: 1px solid #F1F5F9;
  flex-wrap: wrap;
}

.card-pagination {
  display: flex;
  justify-content: flex-end;
}
</style>

// lkda-web-react/src/views/volume/VolumeListView.tsx
import { useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from '@tanstack/react-table'
import {
  Search,
  Plus,
  RefreshCw,
  SlidersHorizontal,
  MoreHorizontal,
  Upload,
  Download,
  Eye,
  Edit3,
  BookOpen,
  LayoutList,
  LayoutGrid,
} from 'lucide-react'

import PageHeader from '@/components/PageHeader'
import { VirtualCardList } from '@/components/VirtualCardList'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select'
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerBody,
  DrawerFooter,
  DrawerCloseButton,
} from '@/components/ui/drawer'
import {
  Popover,
  PopoverTrigger,
  PopoverContent,
} from '@/components/ui/popover'
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@/components/ui/table'
import {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
} from '@/components/ui/tooltip'
import Pagination from '@/components/ui/pagination'
import EmptyState from '@/components/EmptyState'
import StatusTag from '@/components/StatusTag'
import { VolumeApi, type VolumeQueryDTO } from '@/api/volume'
import { useAuthStore } from '@/stores/authStore'
import { useDictStore } from '@/stores/dictStore'
import type { ArchiveVolumeListVO } from '@/types/vo'
import { cn } from '@/lib/utils'

/* ── 常量 ───────────────────────────────────────────────────── */
const PAGE_SIZE = 20

const STATUS_OPTIONS = [
  { label: '草稿', value: '0' },
  { label: '待审核', value: '1' },
  { label: '待确认', value: '2' },
  { label: '已归档', value: '3' },
]

const STOCK_OPTIONS = [
  { label: '在库', value: '1' },
  { label: '借出', value: '0' },
]

const SECURITY_CLASS: Record<string, string> = {
  public: 'bg-green-50 text-green-700',
  internal: 'bg-blue-50 text-blue-700',
  secret: 'bg-yellow-50 text-yellow-700',
  confidential: 'bg-orange-50 text-orange-700',
  topsecret: 'bg-red-50 text-red-700',
}

/* ── 年度选项（2018 - 当前年）────────────────────────────────── */
const currentYear = new Date().getFullYear()
const YEAR_OPTIONS = Array.from({ length: currentYear - 2017 }, (_, i) =>
  String(currentYear - i)
)

/* ── 案卷状态值（含销毁待审批）────────────────────────────────── */
function archiveStatusValue(row: ArchiveVolumeListVO): number {
  if (row.pendingDestroy === 1) return 10
  return row.status
}

/* ── 页面组件 ───────────────────────────────────────────────── */
export default function VolumeListView() {
  const navigate = useNavigate()
  const authStore = useAuthStore()
  const dictStore = useDictStore()
  const isAdmin = authStore.isAdmin

  const [query, setQuery] = useState<VolumeQueryDTO>({
    current: 1,
    size: PAGE_SIZE,
  })
  const [filterOpen, setFilterOpen] = useState(false)
  const [viewMode, setViewMode] = useState<'table' | 'card'>('table')

  /* ── 字典数据 ─────────────────────────────────────────────── */
  const categoryL1Options = dictStore.getItems('category_l1')
  const categoryL2Options = dictStore.getItems('category_l2')

  /* ── 数据查询 ─────────────────────────────────────────────── */
  const { data: pageData, isLoading } = useQuery({
    queryKey: ['volume', 'page', query],
    queryFn: () =>
      VolumeApi.page({
        ...query,
        keyword: query.keyword || undefined,
      }),
  })

  const records = pageData?.records ?? []
  const totalPages = Math.ceil((pageData?.total ?? 0) / PAGE_SIZE)

  /* ── 表格 ─────────────────────────────────────────────────── */
  const columnHelper = createColumnHelper<ArchiveVolumeListVO>()

  const columns = useMemo(
    () => [
      columnHelper.accessor('archiveNo', {
        header: '档号',
        cell: (info) => (
          <span className="font-mono text-xs text-slate-body">
            {info.getValue()}
          </span>
        ),
      }),
      columnHelper.accessor('volumeTitle', {
        header: '案卷题名',
        cell: (info) => (
          <span className="font-medium text-slate-title max-w-[200px] truncate block">
            {info.getValue()}
          </span>
        ),
      }),
      columnHelper.accessor('year', {
        header: '年度',
        cell: (info) => (
          <span className="whitespace-nowrap">{info.getValue()} 年</span>
        ),
      }),
      columnHelper.accessor('categoryL1Label', {
        header: '一级类目',
        cell: (info) => (
          <span className="whitespace-nowrap">{info.getValue() || '—'}</span>
        ),
      }),
      columnHelper.accessor('securityLevelLabel', {
        header: '密级',
        cell: (info) => {
          const val = info.row.original.securityLevel
          const label = info.getValue() || val || '—'
          return (
            <span
              className={cn(
                'inline-flex items-center rounded-tag px-2 py-0.5 text-xs font-medium whitespace-nowrap',
                SECURITY_CLASS[val] ?? 'bg-slate-100 text-slate-600'
              )}
            >
              {label}
            </span>
          )
        },
      }),
      columnHelper.accessor('retentionPeriodLabel', {
        header: '保管期限',
        cell: (info) => (
          <span className="whitespace-nowrap">{info.getValue() || '—'}</span>
        ),
      }),
      columnHelper.accessor('status', {
        header: '归档状态',
        cell: (info) => (
          <span className="whitespace-nowrap">
            <StatusTag
              type="archive"
              value={archiveStatusValue(info.row.original)}
            />
          </span>
        ),
      }),
      columnHelper.accessor('inStock', {
        header: '在库',
        cell: (info) => (
          <span className="whitespace-nowrap">
            <StatusTag type="stock" value={info.getValue()} />
          </span>
        ),
      }),
      columnHelper.display({
        id: 'actions',
        header: '操作',
        cell: ({ row }) => {
          const vol = row.original
          return (
            <TooltipProvider delayDuration={300}>
              <div className="flex items-center gap-0.5">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7 text-primary hover:bg-primary/10"
                      onClick={() => goDetail(vol)}
                    >
                      <Eye size={14} />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>查看</TooltipContent>
                </Tooltip>

                {vol.status === 0 && (
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-primary hover:bg-primary/10"
                        onClick={() => goEdit(vol)}
                      >
                        <Edit3 size={14} />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>编辑</TooltipContent>
                  </Tooltip>
                )}

                {vol.status === 3 && vol.inStock === 1 && (
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-green-600 hover:bg-green-50"
                        onClick={() => goBorrow(vol)}
                      >
                        <BookOpen size={14} />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>借阅</TooltipContent>
                  </Tooltip>
                )}
              </div>
            </TooltipProvider>
          )
        },
      }),
    ],
    []
  )

  const table = useReactTable({
    data: records,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })

  /* ── 事件处理 ─────────────────────────────────────────────── */
  function handleSearch() {
    setQuery((prev) => ({ ...prev, current: 1 }))
  }

  function handleReset() {
    setQuery({
      current: 1,
      size: PAGE_SIZE,
    })
  }

  function goDetail(vol: ArchiveVolumeListVO) {
    navigate(`/volume/detail/${vol.recordId}?year=${vol.year}`)
  }

  function goEdit(vol: ArchiveVolumeListVO) {
    navigate(`/volume/edit/${vol.recordId}?year=${vol.year}`)
  }

  function goBorrow(vol: ArchiveVolumeListVO) {
    navigate(`/borrow/apply/${encodeURIComponent(vol.archiveNo)}`)
  }

  function goNew() {
    navigate('/volume/edit')
  }

  function goImport() {
    navigate('/volume/import')
  }

  /* ── 筛选表单渲染（复用于电脑端和手机端 Drawer）────────────── */
  const filterForm = (
    <div className="space-y-4 md:flex md:flex-wrap md:items-center md:gap-2 md:space-y-0">
      <div className="md:w-[120px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">年度</label>
        <Select
          value={query.year ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({ ...prev, year: v === '_all' ? undefined : v, current: 1 }))
          }
        >
          <SelectTrigger>
            <SelectValue placeholder="年度" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="_all">全部年度</SelectItem>
            {YEAR_OPTIONS.map((y) => (
              <SelectItem key={y} value={y}>
                {y} 年
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[140px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">一级类目</label>
        <Select
          value={query.categoryL1 ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({
              ...prev,
              categoryL1: v === '_all' ? undefined : v,
              categoryL2: undefined,
              current: 1,
            }))
          }
        >
          <SelectTrigger>
            <SelectValue placeholder="一级类目" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="_all">全部类目</SelectItem>
            {categoryL1Options.map((item) => (
              <SelectItem key={item.itemValue} value={item.itemValue}>
                {item.itemLabel}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[140px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">二级类目</label>
        <Select
          value={query.categoryL2 ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({ ...prev, categoryL2: v === '_all' ? undefined : v, current: 1 }))
          }
          disabled={!query.categoryL1}
        >
          <SelectTrigger>
            <SelectValue placeholder="二级类目" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="_all">全部类目</SelectItem>
            {categoryL2Options.map((item) => (
              <SelectItem key={item.itemValue} value={item.itemValue}>
                {item.itemLabel}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[120px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">归档状态</label>
        <Select
          value={query.status?.toString() ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({
              ...prev,
              status: v === '_all' ? undefined : Number(v),
              current: 1,
            }))
          }
        >
          <SelectTrigger>
            <SelectValue placeholder="归档状态" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="_all">全部状态</SelectItem>
            {STATUS_OPTIONS.map((s) => (
              <SelectItem key={s.value} value={s.value}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[105px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">在库状态</label>
        <Select
          value={query.inStock?.toString() ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({
              ...prev,
              inStock: v === '_all' ? undefined : Number(v),
              current: 1,
            }))
          }
        >
          <SelectTrigger>
            <SelectValue placeholder="在库状态" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="_all">全部</SelectItem>
            {STOCK_OPTIONS.map((s) => (
              <SelectItem key={s.value} value={s.value}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[200px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">关键词</label>
        <Input
          placeholder="题名 / 档号 / 主题词"
          value={query.keyword ?? ''}
          onChange={(e) =>
            setQuery((prev) => ({ ...prev, keyword: e.target.value, current: 1 }))
          }
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
        />
      </div>
    </div>
  )

  return (
    <div>
      {/* ── 手机端标题行 ───────────────────────────────────────── */}
      <PageHeader title={<span className="inline-flex items-center gap-2"><BookOpen size={20} className="text-primary-dark" />案卷目录</span>} className="md:hidden" />

      {/* ── 电脑端：标题 + 操作按钮合并为一行 ──────────────────── */}
      <div className="mb-3 hidden md:flex md:items-center md:justify-between">
        <h2 className="inline-flex items-center gap-2 text-xl font-bold text-slate-title"><BookOpen size={20} className="text-primary-dark" />案卷目录</h2>
        <div className="flex items-center gap-2">
          <Button onClick={goNew}>
            <Plus size={16} />
            新建案卷
          </Button>
          {isAdmin && (
            <Button variant="outline" onClick={goImport}>
              <Upload size={16} />
              批量导入
            </Button>
          )}
          <Button variant="outline">
            <Download size={16} />
            导出列表
          </Button>
          <div className="ml-1 flex items-center gap-1">
            <Button
              variant={viewMode === 'table' ? 'primary' : 'outline'}
              size="icon"
              className="h-8 w-8"
              onClick={() => setViewMode('table')}
            >
              <LayoutList size={14} />
            </Button>
            <Button
              variant={viewMode === 'card' ? 'primary' : 'outline'}
              size="icon"
              className="h-8 w-8"
              onClick={() => setViewMode('card')}
            >
              <LayoutGrid size={14} />
            </Button>
          </div>
        </div>
      </div>

      {/* ── 电脑端检索区（紧凑单行）────────────────────────────── */}
      <div className="mb-3 hidden rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] px-4 py-2.5 md:block">
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex-1 min-w-0">
            {filterForm}
          </div>
          <div className="flex shrink-0 gap-2">
            <Button onClick={handleSearch}>
              <Search size={16} />
              检索
            </Button>
            <Button variant="outline" onClick={handleReset}>
              <RefreshCw size={16} />
              重置
            </Button>
          </div>
        </div>
      </div>

      {/* ── 手机端检索栏 ───────────────────────────────────────── */}
      <div className="mb-4 flex gap-2 md:hidden">
        <Input
          placeholder="案卷题名 / 档号 / 主题词"
          value={query.keyword ?? ''}
          onChange={(e) =>
            setQuery((prev) => ({ ...prev, keyword: e.target.value, current: 1 }))
          }
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="flex-1"
        />
        <Button variant="outline" onClick={() => setFilterOpen(true)}>
          <SlidersHorizontal size={16} />
          筛选
        </Button>
      </div>

      {/* ── 手机端工具栏 ───────────────────────────────────────── */}
      <div className="mb-4 flex items-center gap-2 md:hidden">
        <Button onClick={goNew} size="sm">
          <Plus size={16} />
          新建
        </Button>
        <Popover>
          <PopoverTrigger asChild>
            <Button variant="outline" size="sm">
              <MoreHorizontal size={16} />
              更多
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-44 p-2">
            <div className="flex flex-col gap-1">
              {isAdmin && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="justify-start"
                  onClick={goImport}
                >
                  <Upload size={14} className="mr-2" />
                  批量导入
                </Button>
              )}
              <Button variant="ghost" size="sm" className="justify-start">
                <Download size={14} className="mr-2" />
                导出列表
              </Button>
              <div className="my-1 h-px bg-[var(--color-border-light)]" />
              <Button
                variant="ghost"
                size="sm"
                className="justify-start"
                onClick={() => setViewMode('table')}
              >
                <LayoutList size={14} className="mr-2" />
                表格视图
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="justify-start"
                onClick={() => setViewMode('card')}
              >
                <LayoutGrid size={14} className="mr-2" />
                卡片视图
              </Button>
            </div>
          </PopoverContent>
        </Popover>
      </div>

      {/* ── 内容区 ─────────────────────────────────────────────── */}
      <div className="overflow-hidden rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)]">
        {/* 统计栏 */}
        <div className="flex items-center justify-between border-b border-[var(--color-border-light)] px-5 py-3">
          <span className="text-sm text-slate-body">
            共 <strong className="text-primary-dark">{pageData?.total ?? 0}</strong> 条记录
          </span>
        </div>

        {/* 电脑端表格视图 */}
        {(viewMode === 'table') && (
          <div className="hidden md:block overflow-auto">
            {isLoading ? (
              <div className="space-y-3 p-8">
                {Array.from({ length: 5 }).map((_, i) => (
                  <div key={i} className="h-10 animate-pulse rounded bg-slate-100" />
                ))}
              </div>
            ) : records.length === 0 ? (
              <div className="py-12">
                <EmptyState description="暂无案卷数据，试试调整检索条件" />
              </div>
            ) : (
              <Table>
                <TableHeader>
                  {table.getHeaderGroups().map((hg) => (
                    <tr key={hg.id}>
                      {hg.headers.map((h) => (
                        <TableHead key={h.id}>
                          {h.isPlaceholder
                            ? null
                            : flexRender(h.column.columnDef.header, h.getContext())}
                        </TableHead>
                      ))}
                    </tr>
                  ))}
                </TableHeader>
                <TableBody>
                  {table.getRowModel().rows.map((row) => (
                    <TableRow
                      key={row.id}
                      className="cursor-pointer"
                      onClick={() => goDetail(row.original)}
                    >
                      {row.getVisibleCells().map((cell) => (
                        <TableCell key={cell.id}>
                          {flexRender(cell.column.columnDef.cell, cell.getContext())}
                        </TableCell>
                      ))}
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </div>
        )}

        {/* 电脑端卡片视图 */}
        {(viewMode === 'card') && (
          <div className="hidden md:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-4">
            {isLoading
              ? Array.from({ length: 8 }).map((_, i) => (
                  <div key={i} className="h-48 animate-pulse rounded-card bg-slate-100" />
                ))
              : records.length === 0
                ? <EmptyState description="暂无案卷数据，试试调整检索条件" />
                : records.map((vol) => (
                    <div
                      key={`${vol.recordId}-${vol.year}`}
                      className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] p-4 shadow-card cursor-pointer transition-all hover:border-primary hover:shadow-lg hover:-translate-y-0.5"
                      onClick={() => goDetail(vol)}
                    >
                      <div className="mb-3 flex items-start justify-between">
                        <div>
                          <div className="mb-1 font-mono text-xs text-slate-400">
                            {vol.archiveNo}
                          </div>
                          <div className="text-sm font-semibold text-slate-title line-clamp-2">
                            {vol.volumeTitle}
                          </div>
                        </div>
                      </div>
                      <div className="mb-3 space-y-1.5 text-sm text-slate-body">
                        <div className="flex justify-between">
                          <span>年度</span>
                          <span>{vol.year} 年</span>
                        </div>
                        <div className="flex justify-between">
                          <span>一级类目</span>
                          <span>{vol.categoryL1Label || vol.categoryL1 || '—'}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>密级</span>
                          <span>{vol.securityLevelLabel || vol.securityLevel || '—'}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>保管期限</span>
                          <span>{vol.retentionPeriodLabel || vol.retentionPeriod || '—'}</span>
                        </div>
                      </div>
                      <div className="flex items-center justify-between border-t border-[var(--color-border-light)] pt-3">
                        <div className="flex gap-2">
                          <StatusTag type="archive" value={archiveStatusValue(vol)} />
                          <StatusTag type="stock" value={vol.inStock} />
                        </div>
                        {vol.status === 3 && vol.inStock === 1 && (
                          <Button
                            variant="link"
                            size="sm"
                            className="h-7 px-1 text-green-600"
                            onClick={(e) => {
                              e.stopPropagation()
                              goBorrow(vol)
                            }}
                          >
                            <BookOpen size={13} className="mr-0.5" />
                            借阅
                          </Button>
                        )}
                      </div>
                    </div>
                  ))}
          </div>
        )}

        {/* 手机端卡片列表（始终卡片，无视图切换）—— 使用虚拟滚动优化长列表性能 */}
        <div
          className="md:hidden p-3 overscroll-contain"
          style={{ height: 'calc(100dvh - 200px)' }}
        >
          <VirtualCardList
            items={records}
            estimateSize={190}
            overscan={4}
            className="h-full"
            loading={isLoading}
            loadingSkeleton={
              <div className="space-y-3">
                {Array.from({ length: 4 }).map((_, i) => (
                  <div key={i} className="h-44 animate-pulse rounded-card bg-slate-100" />
                ))}
              </div>
            }
            emptyState={<EmptyState description="暂无案卷数据，试试调整检索条件" />}
            renderItem={(vol, idx) => (
              <div
                className={cn(
                  'rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] p-4 shadow-card active:scale-[0.99] transition-transform',
                  idx < records.length - 1 && 'mb-3'
                )}
                onClick={() => goDetail(vol)}
              >
                <div className="mb-2 flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="mb-0.5 font-mono text-[11px] text-slate-400 truncate">
                      {vol.archiveNo}
                    </div>
                    <div className="text-sm font-semibold text-slate-title line-clamp-2">
                      {vol.volumeTitle}
                    </div>
                  </div>
                  <StatusTag type="archive" value={archiveStatusValue(vol)} />
                </div>

                <div className="mb-3 grid grid-cols-2 gap-x-4 gap-y-1.5 text-xs text-slate-body">
                  <div className="flex justify-between">
                    <span className="text-slate-400">年度</span>
                    <span>{vol.year} 年</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">在库</span>
                    <StatusTag type="stock" value={vol.inStock} />
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">一级类目</span>
                    <span className="truncate text-right">{vol.categoryL1Label || vol.categoryL1 || '—'}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">密级</span>
                    <span className="truncate text-right">{vol.securityLevelLabel || vol.securityLevel || '—'}</span>
                  </div>
                  <div className="flex justify-between col-span-2">
                    <span className="text-slate-400">保管期限</span>
                    <span>{vol.retentionPeriodLabel || vol.retentionPeriod || '—'}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 border-t border-[var(--color-border-light)] pt-2.5">
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex-1 h-8 text-xs"
                    onClick={(e) => {
                      e.stopPropagation()
                      goDetail(vol)
                    }}
                  >
                    <Eye size={13} className="mr-1" />
                    查看
                  </Button>
                  {vol.status === 0 && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex-1 h-8 text-xs"
                      onClick={(e) => {
                        e.stopPropagation()
                        goEdit(vol)
                      }}
                    >
                      <Edit3 size={13} className="mr-1" />
                      编辑
                    </Button>
                  )}
                  {vol.status === 3 && vol.inStock === 1 && (
                    <Button
                      variant="primary"
                      size="sm"
                      className="flex-1 h-8 text-xs"
                      onClick={(e) => {
                        e.stopPropagation()
                        goBorrow(vol)
                      }}
                    >
                      <BookOpen size={13} className="mr-1" />
                      借阅
                    </Button>
                  )}
                </div>
              </div>
            )}
          />
        </div>

        {/* 分页 */}
        {totalPages > 1 && (
          <div className="border-t border-[var(--color-border-light)] px-5 py-4">
            <Pagination
              current={query.current ?? 1}
              total={totalPages}
              onChange={(p) => setQuery((prev) => ({ ...prev, current: p }))}
            />
          </div>
        )}
      </div>

      {/* ── 手机端筛选 Drawer ──────────────────────────────────── */}
      <Drawer open={filterOpen} onOpenChange={setFilterOpen}>
        <DrawerContent>
          <DrawerHeader>
            <DrawerTitle>筛选条件</DrawerTitle>
            <DrawerCloseButton />
          </DrawerHeader>
          <DrawerBody>{filterForm}</DrawerBody>
          <DrawerFooter>
            <Button variant="outline" onClick={handleReset}>
              <RefreshCw size={16} className="mr-1.5" />
              重置
            </Button>
            <Button
              onClick={() => {
                handleSearch()
                setFilterOpen(false)
              }}
            >
              <Search size={16} className="mr-1.5" />
              检索
            </Button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </div>
  )
}
