// lkda-web/src/views/auth/ProfileView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { desensitizePhone } from '@/utils/desensitize'

const router = useRouter()
const authStore = useAuthStore()
const info = computed(() => authStore.userInfo)

const ROLE_LABEL: Record<string, string> = {
  archive_admin: '档案管理员',
  user: '普通用户',
  company_leader: '公司领导',
}

const roleChips = computed(() => {
  const r = info.value?.role
  return r ? [{ key: r, label: ROLE_LABEL[r] ?? r }] : []
})

const displayPhone = computed(() =>
  info.value?.phone ? desensitizePhone(info.value.phone) : '—',
)

const avatarLetter = computed(() =>
  info.value?.nickname?.[0]?.toUpperCase() ?? 'U',
)

const infoItems = computed(() => [
  { icon: 'User',          label: '用户名',   value: info.value?.username  ?? '—' },
  { icon: 'Avatar',        label: '昵称',     value: info.value?.nickname  ?? '—' },
  { icon: 'Phone',         label: '手机号',   value: displayPhone.value            },
  { icon: 'OfficeBuilding',label: '角色',     value: ROLE_LABEL[info.value?.role ?? ''] ?? '—' },
])
</script>

<template>
  <div class="page-container">
    <PageHeader title="个人中心" />

    <!-- ── 顶部英雄卡：头像 + 姓名 + 角色标签 ──────────────────── -->
    <div class="profile-hero">
      <div class="avatar-ring">
        <div class="avatar-circle">{{ avatarLetter }}</div>
      </div>

      <div class="hero-info">
        <h2 class="hero-name">{{ info?.nickname }}</h2>
        <div class="role-chips">
          <span
            v-for="chip in roleChips"
            :key="chip.key"
            class="role-chip"
            :class="chip.key.toLowerCase()"
          >
            {{ chip.label }}
          </span>
        </div>
      </div>
    </div>

    <!-- ── 基本信息卡 ─────────────────────────────────────────────── -->
    <el-card class="info-card" shadow="never">
      <template #header>
        <div class="card-title">
          <el-icon><InfoFilled /></el-icon>
          基本信息
        </div>
      </template>

      <div class="info-grid">
        <div v-for="item in infoItems" :key="item.label" class="info-item">
          <div class="item-icon-wrap">
            <el-icon><component :is="item.icon" /></el-icon>
          </div>
          <div class="item-body">
            <span class="item-label">{{ item.label }}</span>
            <span class="item-value">{{ item.value }}</span>
          </div>
        </div>
      </div>
    </el-card>

    <!-- ── 安全设置卡 ─────────────────────────────────────────────── -->
    <el-card class="security-card" shadow="never">
      <template #header>
        <div class="card-title">
          <el-icon><Lock /></el-icon>
          账号安全
        </div>
      </template>

      <div class="security-row">
        <div class="security-left">
          <div class="security-label">登录密码</div>
          <div class="security-desc">定期修改密码有助于保护账号安全</div>
        </div>
        <el-button
          class="change-pwd-btn"
          @click="router.push('/profile/password')"
        >
          <el-icon><EditPen /></el-icon>
          修改密码
        </el-button>
      </div>
    </el-card>
  </div>
</template>

<style scoped lang="scss">
.page-container {
  padding: 16px 24px 24px;
  max-width: 760px;
}

// ── 英雄区 ────────────────────────────────────────────────────────
.profile-hero {
  display: flex;
  align-items: center;
  gap: 24px;
  padding: 28px 32px;
  background: linear-gradient(135deg, var(--theme-bg-soft) 0%, var(--theme-bg-light) 100%);
  border: 1px solid var(--theme-bg-lighter);
  border-radius: var(--radius-card);
  margin-bottom: 20px;
  box-shadow: var(--shadow-card);
}

.avatar-ring {
  padding: 4px;
  background: linear-gradient(135deg, $color-primary, $color-primary-dark);
  border-radius: 50%;
  flex-shrink: 0;
}

.avatar-circle {
  width: 76px;
  height: 76px;
  border-radius: 50%;
  background: #fff;
  color: $color-primary-dark;
  font-size: 32px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  line-height: 1;
}

.hero-info {
  .hero-name {
    font-size: 22px;
    font-weight: 700;
    color: $color-text-title;
    margin-bottom: 10px;
  }

  .role-chips {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }

  .role-chip {
    display: inline-flex;
    align-items: center;
    padding: 3px 12px;
    border-radius: var(--radius-tag);
    font-size: 13px;
    font-weight: 500;

    &.role_admin   { background: var(--theme-border-light); color: #065F46; }
    &.role_user    { background: #DBEAFE; color: #1D4ED8; }
    &.role_leader  { background: #EDE9FE; color: #5B21B6; }
  }
}

// ── 卡片通用标题 ─────────────────────────────────────────────────
.card-title {
  display: flex;
  align-items: center;
  gap: 7px;
  font-size: 15px;
  font-weight: 600;
  color: $color-text-title;

  .el-icon {
    color: $color-primary;
    font-size: 16px;
  }
}

// ── 基本信息卡 ───────────────────────────────────────────────────
.info-card {
  margin-bottom: 20px;
  border-radius: var(--radius-card);
  border-color: #E2E8F0;

  :deep(.el-card__header) {
    padding: 16px 24px;
    border-bottom-color: #F1F5F9;
  }

  :deep(.el-card__body) {
    padding: 16px 24px 24px;
  }
}

.info-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;

  @media (max-width: 560px) {
    grid-template-columns: 1fr;
  }
}

.info-item {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 14px 16px;
  background: #F8FAFC;
  border-radius: 12px;
  border: 1px solid #F1F5F9;
  transition: border-color 0.2s;

  &:hover {
    border-color: var(--theme-border-medium);
  }
}

.item-icon-wrap {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  background: linear-gradient(135deg, var(--theme-bg-lighter), var(--theme-border-medium));
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;

  .el-icon {
    color: $color-primary-dark;
    font-size: 16px;
  }
}

.item-body {
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.item-label {
  font-size: 11px;
  color: #94A3B8;
  margin-bottom: 3px;
  letter-spacing: 0.3px;
}

.item-value {
  font-size: 14px;
  font-weight: 500;
  color: $color-text-title;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

// ── 安全设置卡 ───────────────────────────────────────────────────
.security-card {
  border-radius: var(--radius-card);
  border-color: #E2E8F0;

  :deep(.el-card__header) {
    padding: 16px 24px;
    border-bottom-color: #F1F5F9;
  }

  :deep(.el-card__body) {
    padding: 20px 24px;
  }
}

.security-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.security-left {
  .security-label {
    font-size: 14px;
    font-weight: 600;
    color: $color-text-title;
    margin-bottom: 4px;
  }

  .security-desc {
    font-size: 12px;
    color: #94A3B8;
  }
}

.change-pwd-btn {
  flex-shrink: 0;
  border-color: $color-primary;
  color: $color-primary;
  border-radius: var(--radius-btn);
  font-weight: 500;
  transition: background 0.2s, color 0.2s, transform 0.2s;

  &:hover {
    background: $color-primary;
    color: #fff;
    transform: translateY(-1px);
  }
}
</style>

// lkda-web-react/src/views/auth/ProfileView.tsx
import { useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'
import { cn } from '@/lib/utils'
import { desensitizePhone } from '@/lib/desensitize'
import PageHeader from '@/components/PageHeader'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { User, Smile, Smartphone, Shield, Lock, Edit3 } from 'lucide-react'

const ROLE_LABEL: Record<string, string> = {
  archive_admin: '档案管理员',
  user: '普通用户',
  company_leader: '公司领导',
}

const ROLE_VARIANT: Record<string, 'default' | 'success' | 'warning' | 'danger'> = {
  archive_admin: 'success',
  user: 'default',
  company_leader: 'warning',
}

export default function ProfileView() {
  const navigate = useNavigate()
  const { userInfo } = useAuthStore()

  const avatarLetter = userInfo?.nickname?.[0]?.toUpperCase() ?? 'U'
  const role = userInfo?.role ?? ''
  const roleLabel = ROLE_LABEL[role] ?? role

  const infoItems = [
    { icon: User, label: '用户名', value: userInfo?.username ?? '—' },
    { icon: Smile, label: '昵称', value: userInfo?.nickname ?? '—' },
    { icon: Smartphone, label: '手机号', value: userInfo?.phone ? desensitizePhone(userInfo.phone) : '—' },
    { icon: Shield, label: '角色', value: roleLabel },
  ]

  return (
    <div className="max-w-3xl mx-auto space-y-5">
      <PageHeader title="个人中心" />

      {/* Hero Card */}
      <div
        className={cn(
          'flex items-center gap-6 p-6 md:p-7 rounded-card border border-[var(--color-border-light)] bg-gradient-to-br from-[var(--color-bg-soft)] to-[var(--color-bg-lighter)] shadow-card'
        )}
      >
        <div className="p-[3px] rounded-full bg-gradient-to-br from-primary to-primary-dark flex-shrink-0">
          <div className="w-[72px] h-[72px] md:w-[76px] md:h-[76px] rounded-full bg-white flex items-center justify-center text-primary-dark text-[28px] md:text-[32px] font-bold">
            {avatarLetter}
          </div>
        </div>
        <div>
          <h2 className="text-xl md:text-[22px] font-bold text-[var(--color-slate-title)] mb-2">
            {userInfo?.nickname}
          </h2>
          <Badge variant={ROLE_VARIANT[role] ?? 'default'}>{roleLabel}</Badge>
        </div>
      </div>

      {/* Basic Info Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-[15px]">
            <User size={16} className="text-primary" />
            基本信息
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {infoItems.map((item) => {
              const Icon = item.icon
              return (
                <div
                  key={item.label}
                  className={cn(
                    'flex items-center gap-3.5 p-3.5 rounded-btn bg-[var(--color-bg-lighter)] border border-transparent hover:border-[var(--color-border-medium)] transition-colors'
                  )}
                >
                  <div className="w-9 h-9 rounded-[10px] bg-gradient-to-br from-[var(--color-bg-lighter)] to-[var(--color-border-light)] flex items-center justify-center flex-shrink-0">
                    <Icon size={16} className="text-primary-dark" />
                  </div>
                  <div className="flex flex-col min-w-0">
                    <span className="text-[11px] text-slate-body tracking-wide">
                      {item.label}
                    </span>
                    <span className="text-sm font-medium text-[var(--color-slate-title)] truncate">
                      {item.value}
                    </span>
                  </div>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Security Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-[15px]">
            <Lock size={16} className="text-primary" />
            账号安全
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="flex items-center justify-between gap-4">
            <div>
              <div className="text-sm font-semibold text-[var(--color-slate-title)]">
                登录密码
              </div>
              <div className="text-xs text-slate-body mt-1">
                定期修改密码有助于保护账号安全
              </div>
            </div>
            <Button
              variant="outline"
              size="sm"
              className="shrink-0 border-primary text-primary hover:bg-primary hover:text-white transition-colors"
              onClick={() => navigate('/profile/password')}
            >
              <Edit3 size={14} className="mr-1" />
              修改密码
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
