// lkda-web-react/src/views/volume/VolumeDetailView.tsx
import { useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import {
  ArrowLeft,
  Edit,
  Send,
  BookOpen,
  Files,
  Printer,
  Trash2,
  Check,
  Clock,
  UserCheck,
  FolderCheck,
  FileCheck,
  MoreHorizontal,
} from 'lucide-react'

import PageHeader from '@/components/PageHeader'
import { Button } from '@/components/ui/button'
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from '@/components/ui/tabs'
import {
  Popover,
  PopoverTrigger,
  PopoverContent,
} from '@/components/ui/popover'
import StatusTag from '@/components/StatusTag'
import EmptyState from '@/components/EmptyState'
import { VolumeApi } from '@/api/volume'
import { useAuthStore } from '@/stores/authStore'
import { useDictStore } from '@/stores/dictStore'
import type { ArchiveVolumeDetailVO, ApproveLogVO } from '@/types/vo'
import { cn } from '@/lib/utils'

/* ── 常量 ───────────────────────────────────────────────────── */
const STEPS = [
  { label: '草稿', icon: Edit },
  { label: '待审核', icon: Clock },
  { label: '待确认', icon: UserCheck },
  { label: '已归档', icon: FolderCheck },
]

const ACTION_STYLE: Record<string, { label: string; className: string }> = {
  PASS: { label: '通过', className: 'bg-emerald-50 text-emerald-700' },
  REJECT: { label: '驳回', className: 'bg-red-50 text-red-700' },
  BACK: { label: '退回', className: 'bg-blue-50 text-blue-700' },
}

const BIZ_TYPE: Record<number, string> = {
  1: '归档审核',
  2: '归档确认',
  3: '借阅审批',
  4: '销毁审批',
}

/* ── 状态元数据 ─────────────────────────────────────────────── */
const STATUS_META: Record<number, { text: string; className: string }> = {
  0: { text: '草稿', className: 'bg-slate-100 text-slate-600' },
  1: { text: '待审核', className: 'bg-yellow-50 text-yellow-700' },
  2: { text: '待确认', className: 'bg-blue-50 text-blue-700' },
  3: { text: '已归档', className: 'bg-emerald-50 text-emerald-700' },
  10: { text: '销毁待审批', className: 'bg-violet-50 text-violet-700' },
  11: { text: '已销毁', className: 'bg-red-50 text-red-700' },
}

function resolveStatusMeta(detail: ArchiveVolumeDetailVO | null) {
  if (!detail) return STATUS_META[0]
  if (detail.destroyFlag === 1) return STATUS_META[11]
  if (detail.pendingDestroy === 1) return STATUS_META[10]
  return STATUS_META[detail.status] ?? STATUS_META[0]
}

/* ── Stepper 组件 ───────────────────────────────────────────── */
function Stepper({ activeIndex }: { activeIndex: number }) {
  return (
    <div className="flex items-center justify-between gap-2 md:gap-4">
      {STEPS.map((step, idx) => {
        const Icon = step.icon
        const isCompleted = idx < activeIndex
        const isCurrent = idx === activeIndex
        const isPending = idx > activeIndex

        return (
          <div key={step.label} className="flex flex-1 items-center">
            <div className="flex flex-col items-center gap-2">
              <div
                className={cn(
                  'flex h-9 w-9 items-center justify-center rounded-full border-2 text-sm font-semibold transition-colors md:h-10 md:w-10',
                  isCompleted && 'border-primary bg-primary text-white',
                  isCurrent && 'border-primary bg-primary/10 text-primary',
                  isPending && 'border-slate-200 bg-white text-slate-400'
                )}
              >
                {isCompleted ? (
                  <Check size={18} />
                ) : (
                  <Icon size={16} />
                )}
              </div>
              <span
                className={cn(
                  'text-xs font-medium md:text-sm',
                  isCompleted && 'text-primary-dark',
                  isCurrent && 'text-primary font-semibold',
                  isPending && 'text-slate-400'
                )}
              >
                {step.label}
              </span>
            </div>
            {idx < STEPS.length - 1 && (
              <div
                className={cn(
                  'mx-1 h-0.5 flex-1 rounded-full md:mx-2',
                  idx < activeIndex ? 'bg-primary' : 'bg-slate-200'
                )}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}

/* ── 信息项组件 ─────────────────────────────────────────────── */
function InfoItem({
  label,
  children,
  className,
}: {
  label: string
  children: React.ReactNode
  className?: string
}) {
  return (
    <div className={cn('flex flex-col gap-1', className)}>
      <span className="text-xs font-medium text-slate-400">{label}</span>
      <span className="break-words text-sm text-slate-title">
        {children ?? '—'}
      </span>
    </div>
  )
}

/* ── 审批历史时间线 ─────────────────────────────────────────── */
function ApprovalTimeline({ logs, loading }: { logs: ApproveLogVO[]; loading: boolean }) {
  if (loading) {
    return (
      <div className="space-y-4 py-4">
        {Array.from({ length: 3 }).map((_, i) => (
          <div key={i} className="h-20 animate-pulse rounded-card bg-slate-100" />
        ))}
      </div>
    )
  }

  if (logs.length === 0) {
    return <EmptyState description="暂无审批记录" />
  }

  return (
    <div className="relative py-4">
      {/* 竖线 */}
      <div className="absolute left-[11px] top-4 bottom-4 w-px bg-[var(--color-border-light)] md:left-[15px]" />

      <div className="space-y-5">
        {logs.map((log) => {
          const action = ACTION_STYLE[log.action] ?? {
            label: log.action,
            className: 'bg-slate-100 text-slate-600',
          }
          return (
            <div key={log.logId} className="relative flex gap-4 pl-1 md:gap-5">
              {/* 圆点 */}
              <div
                className={cn(
                  'z-10 mt-1.5 h-3 w-3 shrink-0 rounded-full border-2 border-white shadow-sm md:h-4 md:w-4',
                  log.action === 'PASS'
                    ? 'bg-emerald-500'
                    : log.action === 'REJECT'
                      ? 'bg-red-500'
                      : 'bg-blue-500'
                )}
              />

              {/* 内容卡片 */}
              <div className="flex-1 rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] p-3 shadow-sm md:p-4">
                <div className="mb-2 flex flex-wrap items-center gap-2">
                  <span className="text-sm font-medium text-slate-body">
                    {BIZ_TYPE[log.businessType] ?? '审批'}
                  </span>
                  <span
                    className={cn(
                      'inline-flex items-center rounded-tag px-2 py-0.5 text-xs font-semibold',
                      action.className
                    )}
                  >
                    {action.label}
                  </span>
                  <span className="ml-auto flex items-center gap-1 text-xs text-slate-title">
                    <UserCheck size={12} className="text-slate-400" />
                    {log.approverName}
                  </span>
                </div>
                {log.opinion && (
                  <p className="rounded-lg bg-[var(--color-bg-lighter)] p-2.5 text-sm leading-relaxed text-slate-body">
                    {log.opinion}
                  </p>
                )}
                <p className="mt-2 text-xs text-slate-400">
                  {log.createdAt?.slice(0, 16).replace('T', ' ')}
                </p>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

/* ── 页面组件 ───────────────────────────────────────────────── */
export default function VolumeDetailView() {
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const [searchParams] = useSearchParams()
  const queryClient = useQueryClient()
  const authStore = useAuthStore()
  const dictStore = useDictStore()

  const recordId = Number(id)
  const year = searchParams.get('year') ?? ''

  const [activeTab, setActiveTab] = useState('location')

  /* ── 数据查询 ─────────────────────────────────────────────── */
  const {
    data: detail,
    isLoading: detailLoading,
  } = useQuery({
    queryKey: ['volume', 'detail', recordId, year],
    queryFn: () => VolumeApi.detail(recordId, year),
    enabled: !!recordId && !!year,
  })

  const {
    data: logs,
    isLoading: logLoading,
  } = useQuery({
    queryKey: ['volume', 'logs', recordId],
    queryFn: () => VolumeApi.approveLogs(recordId),
    enabled: !!recordId,
  })

  /* ── 权限计算 ─────────────────────────────────────────────── */
  const isAdmin = authStore.isAdmin
  const isLeader = authStore.isLeader
  const userId = authStore.userInfo?.userId

  const isCompilerOrAdmin =
    isAdmin || (detail?.compilerId != null && detail.compilerId === userId)

  const showEdit = detail?.status === 0 && isCompilerOrAdmin
  const showSubmit = detail?.status === 0 && isCompilerOrAdmin
  const showBorrow =
    detail?.status === 3 &&
    detail.inStock === 1 &&
    (detail.borrowedCopies ?? 0) < (detail.copies ?? 1) &&
    !isAdmin &&
    !isLeader
  const showPrint = (detail?.status ?? 0) >= 1
  const showDestroy =
    detail?.status === 3 && detail.destroyFlag === 0 && isAdmin

  /* ── 操作 ─────────────────────────────────────────────────── */
  const submitMutation = useMutation({
    mutationFn: () => VolumeApi.submit(recordId, year),
    onSuccess: () => {
      toast.success('已提交审核')
      queryClient.invalidateQueries({ queryKey: ['volume', 'detail'] })
    },
  })

  function handleSubmit() {
    if (!window.confirm('提交审核后，案卷将进入待审核状态，不可再编辑，确认提交？'))
      return
    submitMutation.mutate()
  }

  function goEdit() {
    navigate(`/volume/edit/${recordId}?year=${year}`)
  }

  function goBorrow() {
    if (!detail) return
    navigate(`/borrow/apply/${encodeURIComponent(detail.archiveNo)}`)
  }

  function goFiles() {
    navigate(`/file/list/${recordId}?year=${year}`)
  }

  function goPrint() {
    navigate(`/print/preview/${recordId}?year=${year}`)
  }

  function goDestroy() {
    navigate(`/destroy/apply?recordId=${recordId}&year=${year}`)
  }

  /* ── 字典标签 ─────────────────────────────────────────────── */
  const dictLabel = (code: string, value?: string | null) =>
    dictStore.getLabel(code, value ?? '') || value || '—'

  /* ── 加载态 ───────────────────────────────────────────────── */
  if (detailLoading) {
    return (
      <div className="p-3 md:p-4">
        <PageHeader title="案卷详情" />
        <div className="space-y-4">
          <div className="h-32 animate-pulse rounded-card bg-slate-100" />
          <div className="h-48 animate-pulse rounded-card bg-slate-100" />
          <div className="h-16 animate-pulse rounded-card bg-slate-100" />
        </div>
      </div>
    )
  }

  if (!detail) {
    return (
      <div className="p-3 md:p-4">
        <PageHeader title="案卷详情" />
        <EmptyState description="未找到该案卷，请返回列表重新选择" />
      </div>
    )
  }

  const statusMeta = resolveStatusMeta(detail)
  const stepsActive = Math.min(detail.status, 3)

  return (
    <div className="p-3 md:p-4 pb-28 md:pb-4">
      {/* ── 页头 ─────────────────────────────────────────────── */}
      <div className="mb-3 flex items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <PageHeader title={<span className="inline-flex items-center gap-2"><BookOpen size={20} className="text-primary-dark" />案卷详情</span>} />
          <span
            className={cn(
              'inline-flex items-center rounded-tag px-3 py-1 text-xs font-semibold',
              statusMeta.className
            )}
          >
            {statusMeta.text}
          </span>
        </div>

        {/* 桌面端操作按钮 */}
        <div className="hidden items-center gap-2 md:flex">
          <Button variant="outline" onClick={() => navigate(-1)}>
            <ArrowLeft size={16} className="mr-1.5" />
            返回
          </Button>
          {showEdit && (
            <Button variant="outline" className="border-primary text-primary hover:bg-[var(--color-bg-soft)]" onClick={goEdit}>
              <Edit size={16} className="mr-1.5" />
              编辑
            </Button>
          )}
          {showSubmit && (
            <Button loading={submitMutation.isPending} onClick={handleSubmit}>
              <Send size={16} className="mr-1.5" />
              提交审核
            </Button>
          )}
          {showBorrow && (
            <Button onClick={goBorrow}>
              <BookOpen size={16} className="mr-1.5" />
              申请借阅
            </Button>
          )}
          <Button variant="outline" className="border-primary text-primary hover:bg-[var(--color-bg-soft)]" onClick={goFiles}>
            <Files size={16} className="mr-1.5" />
            卷内文件目录
          </Button>
          {showPrint && (
            <Button variant="outline" onClick={goPrint}>
              <Printer size={16} className="mr-1.5" />
              打印
            </Button>
          )}
          {showDestroy && (
            <Button variant="danger" onClick={goDestroy}>
              <Trash2 size={16} className="mr-1.5" />
              申请销毁
            </Button>
          )}
        </div>
      </div>

      {/* ── 状态时间线 ─────────────────────────────────────────── */}
      <div className="mb-3 rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] p-4 shadow-card md:p-5">
        <Stepper activeIndex={stepsActive} />

        {/* 档号横幅 */}
        <div className="mt-3 flex flex-wrap items-start gap-3 rounded-[10px] border border-[var(--color-border-medium)] bg-gradient-to-r from-[var(--color-bg-soft)] to-[var(--color-bg-lighter)] p-3">
          <FileCheck size={22} className="mt-0.5 shrink-0 text-primary" />
          <div className="min-w-0 flex-1">
            <div className="font-mono text-base font-bold tracking-wide text-primary-dark md:text-lg">
              {detail.archiveNo}
            </div>
            <div className="mt-1 text-sm font-medium text-slate-title">
              {detail.volumeTitle}
            </div>
          </div>
        </div>
      </div>

      {/* ── Tabs ───────────────────────────────────────────────── */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <div className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] shadow-card">
          <div className="overflow-x-auto scrollbar-hide">
          <TabsList className="w-max min-w-full justify-start rounded-none rounded-t-card border-b border-[var(--color-border-light)] bg-[var(--color-bg-lighter)] p-0 px-2">
            {[
              { value: 'location', label: '分类定位' },
              { value: 'description', label: '案卷描述' },
              { value: 'flow', label: '流程信息' },
              ...(detail.remark || detail.notes
                ? [{ value: 'notes', label: '备考' }]
                : []),
              { value: 'history', label: '审批历史' },
            ].map((tab) => (
              <TabsTrigger
                key={tab.value}
                value={tab.value}
                className="rounded-none border-b-2 border-transparent px-3 py-3 text-sm data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:shadow-none md:px-5"
              >
                {tab.label}
              </TabsTrigger>
            ))}
          </TabsList>
          </div>

          <div className="p-4 md:p-5">
            {/* 分类定位 */}
            <TabsContent value="location" className="mt-0">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <InfoItem label="全宗号">
                  {dictLabel('fonds_no', detail.fondsNo)}
                </InfoItem>
                <InfoItem label="年度">{detail.year} 年</InfoItem>
                <InfoItem label="一级类目">
                  {detail.categoryL1Label || dictLabel('category_l1', detail.categoryL1)}
                </InfoItem>
                <InfoItem label="二级类目">
                  {detail.categoryL2
                    ? dictLabel('category_l2', detail.categoryL2)
                    : '—'}
                </InfoItem>
                <InfoItem label="三级类目">
                  {detail.categoryL3
                    ? dictLabel('category_l3', detail.categoryL3)
                    : '—'}
                </InfoItem>
                <InfoItem label="设备代号">
                  {dictLabel('equipment_code', detail.deviceCode)}
                </InfoItem>
                <InfoItem label="案卷号">
                  <span className="font-mono">{detail.volumeNo || '—'}</span>
                </InfoItem>
                <InfoItem label="档号" className="sm:col-span-2 lg:col-span-4">
                  <span className="font-mono text-sm font-semibold text-primary-dark">
                    {detail.archiveNo}
                  </span>
                </InfoItem>
              </div>
            </TabsContent>

            {/* 案卷描述 */}
            <TabsContent value="description" className="mt-0">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <InfoItem label="案卷题名" className="sm:col-span-2 lg:col-span-4">
                  <span className="text-base font-semibold">{detail.volumeTitle}</span>
                </InfoItem>
                <InfoItem label="编制单位" className="sm:col-span-2">
                  {detail.compileUnit || '—'}
                </InfoItem>
                <InfoItem label="密级">
                  {detail.securityLevel ? (
                    <span className="inline-flex items-center rounded-tag bg-yellow-50 px-2 py-0.5 text-xs font-semibold text-yellow-700">
                      {detail.securityLevelLabel || detail.securityLevel}
                    </span>
                  ) : (
                    '—'
                  )}
                </InfoItem>
                <InfoItem label="保管期限">
                  {detail.retentionPeriodLabel || detail.retentionPeriod || '—'}
                </InfoItem>
                <InfoItem label="件数">{detail.copies ?? '—'} 件</InfoItem>
                <InfoItem label="页数">
                  {detail.totalPages ? `${detail.totalPages} 页` : '—'}
                </InfoItem>
                <InfoItem label="在库状态">
                  <StatusTag type="stock" value={detail.inStock} />
                </InfoItem>
                <InfoItem label="已借出份数">
                  {detail.borrowedCopies ?? 0} / {detail.copies ?? 1} 份
                </InfoItem>
              </div>
            </TabsContent>

            {/* 流程信息 */}
            <TabsContent value="flow" className="mt-0">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <InfoItem label="立卷人">{detail.compiler || '—'}</InfoItem>
                <InfoItem label="立卷日期">{detail.compileDate || '—'}</InfoItem>
                <InfoItem label="审核人">{detail.reviewer || '—'}</InfoItem>
                <InfoItem label="归档日期">{detail.archiveDate || '—'}</InfoItem>
                <InfoItem label="创建时间">
                  {detail.createdAt?.slice(0, 16).replace('T', ' ')}
                </InfoItem>
                <InfoItem label="最后更新">
                  {detail.updatedAt?.slice(0, 16).replace('T', ' ')}
                </InfoItem>
              </div>
            </TabsContent>

            {/* 备考 */}
            {detail.remark || detail.notes ? (
              <TabsContent value="notes" className="mt-0">
                <div className="grid grid-cols-1 gap-4">
                  {detail.remark && (
                    <InfoItem label="备考说明">
                      <p className="whitespace-pre-wrap rounded-lg bg-[var(--color-bg-lighter)] p-3 text-sm leading-relaxed text-slate-body">
                        {detail.remark}
                      </p>
                    </InfoItem>
                  )}
                  {detail.notes && (
                    <InfoItem label="备注">
                      <p className="whitespace-pre-wrap rounded-lg bg-[var(--color-bg-lighter)] p-3 text-sm leading-relaxed text-slate-body">
                        {detail.notes}
                      </p>
                    </InfoItem>
                  )}
                </div>
              </TabsContent>
            ) : null}

            {/* 审批历史 */}
            <TabsContent value="history" className="mt-0">
              <ApprovalTimeline logs={logs ?? []} loading={logLoading} />
            </TabsContent>
          </div>
        </div>
      </Tabs>

      {/* ── 底部操作栏（手机端） ──────────────────────────────────── */}
      <div className="fixed inset-x-0 bottom-0 z-30 border-t border-[var(--color-border-light)] bg-[var(--color-bg-main)] px-4 py-3 shadow-[0_-2px_8px_rgba(0,0,0,0.04)] md:hidden">
        <div className="flex items-center justify-between gap-3">
          <Button variant="outline" onClick={() => navigate(-1)}>
            <ArrowLeft size={16} className="mr-1.5" />
            返回
          </Button>

          {/* 手机端：主要按钮 + 更多Popover */}
          <div className="flex items-center gap-2">
            {showEdit && (
              <Button variant="outline" size="sm" onClick={goEdit}>
                <Edit size={14} className="mr-1" />
                编辑
              </Button>
            )}
            {showSubmit && (
              <Button
                size="sm"
                loading={submitMutation.isPending}
                onClick={handleSubmit}
              >
                <Send size={14} className="mr-1" />
                提交
              </Button>
            )}
            {showBorrow && (
              <Button size="sm" onClick={goBorrow}>
                <BookOpen size={14} className="mr-1" />
                借阅
              </Button>
            )}

            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" size="sm">
                  <MoreHorizontal size={14} />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-48 p-2" align="end">
                <div className="flex flex-col gap-1">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="justify-start"
                    onClick={goFiles}
                  >
                    <Files size={14} className="mr-2" />
                    卷内文件目录
                  </Button>
                  {showPrint && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="justify-start"
                      onClick={goPrint}
                    >
                      <Printer size={14} className="mr-2" />
                      打印
                    </Button>
                  )}
                  {showDestroy && (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="justify-start text-red-600 hover:text-red-700 hover:bg-red-50"
                      onClick={goDestroy}
                    >
                      <Trash2 size={14} className="mr-2" />
                      申请销毁
                    </Button>
                  )}
                </div>
              </PopoverContent>
            </Popover>
          </div>
        </div>
      </div>
    </div>
  )
}

// lkda-web/src/views/volume/VolumeDetailView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useDictStore } from '@/stores/dict'
import { useAuthStore } from '@/stores/auth'
import { VolumeApi } from '@/api/volume'
import type { ArchiveVolumeDetailVO, ApproveLogVO } from '@/types/vo'

const route     = useRoute()
const router    = useRouter()
const dictStore = useDictStore()
const authStore = useAuthStore()

const recordId = computed(() => Number(route.params.id))
const year = computed(() => String(route.query.year ?? ''))

// ── 数据 ─────────────────────────────────────────────────────────
const detail   = ref<ArchiveVolumeDetailVO | null>(null)
const logs     = ref<ApproveLogVO[]>([])
const loading  = ref(false)
const logLoading = ref(false)

async function loadDetail() {
  if (!year.value) {
    loading.value = false
    return
  }
  loading.value = true
  try {
    detail.value = await VolumeApi.detail(recordId.value, year.value)
  } finally {
    loading.value = false
  }
}

async function loadLogs() {
  if (!year.value) return
  logLoading.value = true
  try {
    logs.value = await VolumeApi.approveLogs(recordId.value)
  } catch {
    logs.value = []
  } finally {
    logLoading.value = false
  }
}

onMounted(() => {
  loadDetail()
  loadLogs()
})

// ── 权限判断 ─────────────────────────────────────────────────────
const isAdmin  = computed(() => authStore.isAdmin)
const isLeader = computed(() => authStore.isLeader)
const userId   = computed(() => authStore.userInfo?.userId)

// 立卷人本人 或 管理员
const isCompilerOrAdmin = computed(() =>
  isAdmin.value || (detail.value?.compilerId != null && detail.value.compilerId === userId.value)
)

// 操作栏显隐逻辑
const showEdit        = computed(() => detail.value?.status === 0 && isCompilerOrAdmin.value)
const showSubmit      = computed(() => detail.value?.status === 0 && isCompilerOrAdmin.value)
const showBorrow      = computed(() =>
  detail.value?.status === 3
  && detail.value.inStock === 1
  && (detail.value.borrowedCopies ?? 0) < (detail.value.copies ?? 1)
  && !isAdmin.value
  && !isLeader.value
)
const showPrint       = computed(() => (detail.value?.status ?? 0) >= 1)
const showDestroy     = computed(() =>
  detail.value?.status === 3
  && detail.value.destroyFlag === 0
  && isAdmin.value
)

// ── 状态时间线 ───────────────────────────────────────────────────
const STEPS = [
  { label: '草稿',   icon: 'Edit' },
  { label: '待审核', icon: 'Clock' },
  { label: '待确认', icon: 'UserFilled' },
  { label: '已归档', icon: 'FolderChecked' },
]

// el-steps 的 active 值（0-indexed）
const stepsActive = computed(() => {
  if (!detail.value) return 0
  return Math.min(detail.value.status, 3)
})

// ── 字典 label 工具 ──────────────────────────────────────────────
const label = (code: string, value: string) => dictStore.getDictLabel(code, value) || value || '—'

// ── 提交审核 ─────────────────────────────────────────────────────
const activeTab = ref('location')
const submitting = ref(false)
async function handleSubmit() {
  await ElMessageBox.confirm(
    '提交审核后，案卷将进入待审核状态，不可再编辑，确认提交？',
    '确认提交审核',
    { type: 'warning', confirmButtonText: '确认提交', cancelButtonText: '取消' },
  )
  submitting.value = true
  try {
    await VolumeApi.submit(recordId.value, detail.value!.year)
    ElMessage.success('已提交审核')
    await loadDetail()
    loadLogs()
  } finally {
    submitting.value = false
  }
}

// ── 导航 ─────────────────────────────────────────────────────────
const goEdit    = () => router.push({ path: `/volume/edit/${recordId.value}`, query: { year: detail.value?.year } })
const goFiles   = () => router.push({ path: `/file/list/${recordId.value}`, query: { year: detail.value?.year } })
const goPrint   = () => router.push({ path: `/print/preview/${recordId.value}`, query: { year: detail.value?.year } })
const goBorrow  = () => router.push(`/borrow/apply/${detail.value?.archiveNo}`)
const goDestroy = () => router.push({
  path: '/destroy/apply',
  query: {
    recordId: String(recordId.value),
    year: year.value,
  },
})

// ── 审批动作样式 ─────────────────────────────────────────────────
const ACTION_STYLE: Record<string, { label: string; bg: string; color: string }> = {
  PASS:   { label: '通过', bg: 'var(--theme-border-light)', color: '#065F46' },
  REJECT: { label: '驳回', bg: '#FEE2E2', color: '#991B1B' },
  BACK:   { label: '退回', bg: '#DBEAFE', color: '#1D4ED8' },
}
const actionStyle = (action: string) =>
  ACTION_STYLE[action] ?? { label: action, bg: '#F1F5F9', color: '#64748B' }

// ── 业务类型 ─────────────────────────────────────────────────────
const BIZ_TYPE: Record<number, string> = {
  1: '归档审核',
  2: '归档确认',
  3: '借阅审批',
  4: '销毁审批',
}

// ── 档案状态总览 ─────────────────────────────────────────────────
const STATUS_META: Record<number, { text: string; bg: string; color: string }> = {
  0:  { text: '草稿',      bg: '#F1F5F9', color: '#64748B' },
  1:  { text: '待审核',    bg: '#FEF9C3', color: '#854D0E' },
  2:  { text: '待确认',    bg: '#DBEAFE', color: '#1D4ED8' },
  3:  { text: '已归档',    bg: 'var(--theme-border-light)', color: '#065F46' },
  10: { text: '销毁待审批',bg: '#EDE9FE', color: '#5B21B6' },
  11: { text: '已销毁',    bg: '#FEE2E2', color: '#991B1B' },
}
const statusMeta = computed(() => {
  if (!detail.value) return STATUS_META[0]
  if (detail.value.destroyFlag === 1) return STATUS_META[11]
  if (detail.value.pendingDestroy === 1) return STATUS_META[10]
  return STATUS_META[detail.value.status] ?? STATUS_META[0]
})
</script>

<template>
  <div class="page-container" v-loading="loading">
    <!-- ── 页头 ──────────────────────────────────────────────────── -->
    <div class="detail-header">
      <PageHeader
        title="案卷详情"
        show-back
        :breadcrumbs="[
          { label: '案卷管理', path: '/volume/list' },
          { label: '案卷详情' },
        ]"
      />
      <span
        v-if="detail"
        class="status-pill"
        :style="{ color: statusMeta.color, background: statusMeta.bg }"
      >{{ statusMeta.text }}</span>
    </div>

    <template v-if="detail">
      <!-- ── 状态时间线 ──────────────────────────────────────────── -->
      <el-card class="timeline-card" shadow="never">
        <el-steps :active="stepsActive" align-center finish-status="success">
          <el-step
            v-for="(step, idx) in STEPS"
            :key="step.label"
            :title="step.label"
            :status="idx < stepsActive ? 'success' : idx === stepsActive ? 'process' : 'wait'"
          />
        </el-steps>

        <!-- 档号大标题 -->
        <div class="archive-no-banner">
          <el-icon class="banner-icon"><DocumentChecked /></el-icon>
          <span class="banner-no">{{ detail.archiveNo }}</span>
          <span class="banner-title">{{ detail.volumeTitle }}</span>
        </div>
      </el-card>

      <!-- ── Tab 页签内容区 ─────────────────────────────────────── -->
      <el-card class="tabs-card" shadow="never">
        <el-tabs v-model="activeTab" class="detail-tabs">
          <!-- 分类定位 -->
          <el-tab-pane label="分类定位" name="location">
            <div class="tab-pane-body">
              <div class="info-grid">
                <div class="info-item">
                  <span class="info-label">全宗号</span>
                  <span class="info-value">{{ label('fonds_no', detail.fondsNo) }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">年度</span>
                  <span class="info-value">{{ detail.year }} 年</span>
                </div>
                <div class="info-item">
                  <span class="info-label">一级类目</span>
                  <span class="info-value">{{ detail.categoryL1Label || label('category_l1', detail.categoryL1) }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">二级类目</span>
                  <span class="info-value">{{ detail.categoryL2 ? label('category_l2', detail.categoryL2) : '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">三级类目</span>
                  <span class="info-value">{{ detail.categoryL3 ? label('category_l3', detail.categoryL3) : '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">设备代号</span>
                  <span class="info-value">{{ detail.deviceCode ? label('equipment_code', detail.deviceCode) : '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">案卷号</span>
                  <span class="info-value mono">{{ detail.volumeNo || '—' }}</span>
                </div>
                <div class="info-item col-span-4">
                  <span class="info-label">档号</span>
                  <span class="info-value mono highlight">{{ detail.archiveNo }}</span>
                </div>
              </div>
            </div>
          </el-tab-pane>

          <!-- 案卷描述 -->
          <el-tab-pane label="案卷描述" name="description">
            <div class="tab-pane-body">
              <div class="info-grid">
                <div class="info-item col-span-4">
                  <span class="info-label">案卷题名</span>
                  <span class="info-value title-value">{{ detail.volumeTitle }}</span>
                </div>
                <div class="info-item col-span-2">
                  <span class="info-label">编制单位</span>
                  <span class="info-value">{{ detail.compileUnit || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">密级</span>
                  <span class="security-chip" v-if="detail.securityLevel">
                    {{ detail.securityLevelLabel || detail.securityLevel }}
                  </span>
                  <span class="info-value" v-else>—</span>
                </div>
                <div class="info-item">
                  <span class="info-label">保管期限</span>
                  <span class="info-value">{{ detail.retentionPeriodLabel || detail.retentionPeriod || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">件数</span>
                  <span class="info-value">{{ detail.copies ?? '—' }} 件</span>
                </div>
                <div class="info-item">
                  <span class="info-label">页数</span>
                  <span class="info-value">{{ detail.totalPages ? detail.totalPages + ' 页' : '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">在库状态</span>
                  <StatusTag type="stock" :value="detail.inStock" />
                </div>
                <div class="info-item">
                  <span class="info-label">已借出份数</span>
                  <span class="info-value">
                    {{ detail.borrowedCopies ?? 0 }} / {{ detail.copies ?? 1 }} 份
                  </span>
                </div>
              </div>
            </div>
          </el-tab-pane>

          <!-- 流程信息 -->
          <el-tab-pane label="流程信息" name="flow">
            <div class="tab-pane-body">
              <div class="info-grid">
                <div class="info-item">
                  <span class="info-label">立卷人</span>
                  <span class="info-value">{{ detail.compiler || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">立卷日期</span>
                  <span class="info-value">{{ detail.compileDate || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">审核人</span>
                  <span class="info-value">{{ detail.reviewer || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">归档日期</span>
                  <span class="info-value">{{ detail.archiveDate || '—' }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">创建时间</span>
                  <span class="info-value">{{ detail.createdAt }}</span>
                </div>
                <div class="info-item">
                  <span class="info-label">最后更新</span>
                  <span class="info-value">{{ detail.updatedAt }}</span>
                </div>
              </div>
            </div>
          </el-tab-pane>

          <!-- 备考 -->
          <el-tab-pane
            v-if="detail.remark || detail.notes"
            label="备考"
            name="notes"
          >
            <div class="tab-pane-body">
              <div class="info-grid">
                <div v-if="detail.remark" class="info-item col-span-4">
                  <span class="info-label">备考说明</span>
                  <span class="info-value textarea-value">{{ detail.remark }}</span>
                </div>
                <div v-if="detail.notes" class="info-item col-span-4">
                  <span class="info-label">备注</span>
                  <span class="info-value textarea-value">{{ detail.notes }}</span>
                </div>
              </div>
            </div>
          </el-tab-pane>

          <!-- 审批历史 -->
          <el-tab-pane label="审批历史" name="history">
            <div class="tab-pane-body">
              <EmptyState
                v-if="!logLoading && logs.length === 0"
                description="暂无审批记录"
              />

              <el-timeline v-else v-loading="logLoading">
                <el-timeline-item
                  v-for="log in logs"
                  :key="log.logId"
                  :timestamp="log.createdAt"
                  placement="top"
                  :color="ACTION_STYLE[log.action]?.color ?? '#94A3B8'"
                >
                  <el-card class="log-card" shadow="never">
                    <div class="log-header">
                      <span class="log-biz">{{ BIZ_TYPE[log.businessType] ?? '审批' }}</span>
                      <span
                        class="log-action-chip"
                        :style="{
                          background: actionStyle(log.action).bg,
                          color:      actionStyle(log.action).color,
                        }"
                      >{{ actionStyle(log.action).label }}</span>
                      <span class="log-approver">
                        <el-icon><UserFilled /></el-icon>
                        {{ log.approverName }}
                      </span>
                    </div>
                    <p v-if="log.opinion" class="log-opinion">{{ log.opinion }}</p>
                  </el-card>
                </el-timeline-item>
              </el-timeline>
            </div>
          </el-tab-pane>
        </el-tabs>
      </el-card>
    </template>

    <!-- 加载骨架 -->
    <template v-else-if="!loading">
      <EmptyState description="未找到该案卷，请返回列表重新选择" />
    </template>

    <!-- ── 操作栏（固定底部）────────────────────────────────────── -->
    <div v-if="detail" class="action-bar">
      <el-button size="large" @click="router.back()">
        <el-icon><ArrowLeft /></el-icon>
        返回
      </el-button>

      <div class="action-right">
        <!-- 编辑（草稿 & 立卷人/管理员） -->
        <el-button
          v-if="showEdit"
          size="large"
          class="btn-edit"
          @click="goEdit"
        >
          <el-icon><Edit /></el-icon>
          编辑
        </el-button>

        <!-- 提交审核（草稿 & 立卷人/管理员） -->
        <el-button
          v-if="showSubmit"
          type="warning"
          size="large"
          :loading="submitting"
          @click="handleSubmit"
        >
          <el-icon><Promotion /></el-icon>
          提交审核
        </el-button>

        <!-- 申请借阅（已归档 & 在库 & 普通用户） -->
        <el-button
          v-if="showBorrow"
          type="primary"
          size="large"
          @click="goBorrow"
        >
          <el-icon><Suitcase /></el-icon>
          申请借阅
        </el-button>

        <!-- 卷内文件目录（始终可访问） -->
        <el-button
          v-if="detail"
          size="large"
          class="btn-files"
          @click="goFiles"
        >
          <el-icon><Files /></el-icon>
          卷内文件目录
        </el-button>

        <!-- 打印（已提交后均可） -->
        <el-button
          v-if="showPrint"
          size="large"
          class="btn-print"
          @click="goPrint"
        >
          <el-icon><Printer /></el-icon>
          打印
        </el-button>

        <!-- 申请销毁（已归档 & 管理员） -->
        <el-button
          v-if="showDestroy"
          type="danger"
          size="large"
          plain
          @click="goDestroy"
        >
          <el-icon><Delete /></el-icon>
          申请销毁
        </el-button>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.page-container {
  padding: 16px 24px 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  max-width: 1400px;
  overflow-y: auto;
}

// ── 页头行 ────────────────────────────────────────────────────────
.detail-header {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;

  :deep(.page-header) {
    flex: 1;
    margin-bottom: 0;
    padding-bottom: 0;
    border-bottom: none;
  }
}

.status-pill {
  display: inline-flex;
  align-items: center;
  padding: 3px 14px;
  border-radius: var(--radius-tag);
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
}

// ── 状态时间线卡片 ────────────────────────────────────────────────
.timeline-card {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: var(--shadow-card);

  :deep(.el-card__body) {
    padding: 24px 32px 20px;
  }

  :deep(.el-step__title) {
    font-size: 13px;
    font-weight: 500;
  }

  :deep(.el-step__head.is-success .el-step__icon) {
    background: $color-primary;
    border-color: $color-primary;
    color: #fff;
  }

  :deep(.el-step__head.is-process .el-step__icon) {
    background: $color-primary;
    border-color: $color-primary;
    color: #fff;
  }

  :deep(.el-step__title.is-success) {
    color: $color-primary-dark;
  }

  :deep(.el-step__title.is-process) {
    color: $color-primary;
    font-weight: 600;
  }
}

.archive-no-banner {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  margin-top: 20px;
  padding: 14px 20px;
  background: linear-gradient(135deg, var(--theme-bg-soft), var(--theme-bg-light));
  border-radius: 10px;
  border: 1px solid var(--theme-border-medium);
  flex-wrap: wrap;
}

.banner-icon {
  font-size: 22px;
  color: $color-primary;
  flex-shrink: 0;
}

.banner-no {
  font-family: 'JetBrains Mono', Consolas, monospace;
  font-size: 18px;
  font-weight: 700;
  color: $color-primary-dark;
  letter-spacing: 0.5px;
  word-break: break-all;
  line-height: 1.4;
}

.banner-title {
  font-size: 15px;
  color: $color-text-title;
  font-weight: 500;
  padding-left: 12px;
  border-left: 2px solid var(--theme-border-medium);
  flex: 1;
  min-width: 0;
  line-height: 1.5;
  word-break: break-all;
}

// ── Tab 卡片 ──────────────────────────────────────────────────────
.tabs-card {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: var(--shadow-card);

  :deep(.el-card__body) {
    padding: 0;
  }
}

.detail-tabs {
  :deep(.el-tabs__header) {
    margin: 0;
    padding: 0 20px;
    background: var(--theme-bg-card);
    border-bottom: 1px solid #F1F5F9;
  }

  :deep(.el-tabs__nav-wrap::after) {
    height: 1px;
    background-color: #F1F5F9;
  }

  :deep(.el-tabs__item) {
    font-size: 14px;
    font-weight: 500;
    color: #64748B;
    padding: 0 20px;
    height: 48px;
    line-height: 48px;
    transition: all 0.2s ease;

    &:hover {
      color: $color-primary;
    }

    &.is-active {
      color: $color-primary;
      font-weight: 600;
    }
  }

  :deep(.el-tabs__active-bar) {
    background-color: $color-primary;
    height: 3px;
    border-radius: 2px 2px 0 0;
  }

  :deep(.el-tabs__content) {
    padding: 0;
  }
}

.tab-pane-body {
  padding: 20px;
}

// ── 信息卡片（兼容旧样式）──────────────────────────────────────────
.info-card {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: var(--shadow-card);

  :deep(.el-card__header) {
    padding: 14px 20px;
    border-bottom: 1px solid #F1F5F9;
    background: var(--theme-bg-card);
    border-radius: var(--radius-card) var(--radius-card) 0 0;
  }

  :deep(.el-card__body) {
    padding: 20px;
  }
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
}

.section-dot {
  width: 4px;
  height: 18px;
  border-radius: 2px;
  background: linear-gradient(180deg, $color-primary, $color-primary-dark);
  flex-shrink: 0;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: $color-text-title;
}

.log-count {
  margin-left: auto;
  border-radius: var(--radius-tag);
}

// ── 信息网格 ──────────────────────────────────────────────────────
.info-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 20px 16px;

  @media (max-width: 1200px) { grid-template-columns: repeat(3, 1fr); }
  @media (max-width: 960px) { grid-template-columns: repeat(2, 1fr); }
  @media (max-width: 600px) { grid-template-columns: 1fr; }
}

.col-span-2 { grid-column: span 2; }
.col-span-3 { grid-column: span 3; }
.col-span-4 { grid-column: span 4; }

@media (max-width: 1200px) {
  .col-span-2 { grid-column: span 2; }
  .col-span-3 { grid-column: span 3; }
  .col-span-4 { grid-column: span 3; }
}
@media (max-width: 960px) {
  .col-span-2,
  .col-span-3,
  .col-span-4 { grid-column: span 2; }
}
@media (max-width: 600px) {
  .col-span-2,
  .col-span-3,
  .col-span-4 { grid-column: span 1; }
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.info-label {
  font-size: 12px;
  color: #94A3B8;
  font-weight: 500;
  letter-spacing: 0.3px;
}

.info-value {
  font-size: 14px;
  color: $color-text-title;
  font-weight: 400;
  line-height: 1.5;
  word-break: break-all;
  overflow-wrap: break-word;

  &.mono {
    font-family: 'JetBrains Mono', Consolas, monospace;
    font-size: 13px;
    letter-spacing: 0.3px;
  }

  &.highlight {
    color: $color-primary-dark;
    font-weight: 600;
    font-size: 14px;
  }

  &.title-value {
    font-size: 15px;
    font-weight: 600;
    color: $color-text-title;
  }

  &.textarea-value {
    white-space: pre-wrap;
    color: $color-text-body;
    font-size: 13px;
    line-height: 1.7;
    word-break: break-all;
    overflow-wrap: break-word;
    max-height: 300px;
    overflow-y: auto;
  }
}

.security-chip {
  display: inline-flex;
  align-items: center;
  padding: 2px 10px;
  border-radius: var(--radius-tag);
  font-size: 12px;
  font-weight: 600;
  background: #FFFBEB;
  color: #92400E;
  width: fit-content;
}

// ── 审批历史 ──────────────────────────────────────────────────────
.log-card {
  border-radius: 10px;
  border: 1px solid #F1F5F9;

  :deep(.el-card__body) {
    padding: 12px 16px;
  }
}

.log-header {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}

.log-biz {
  font-size: 13px;
  color: $color-text-body;
  font-weight: 500;
}

.log-action-chip {
  display: inline-flex;
  align-items: center;
  padding: 2px 10px;
  border-radius: var(--radius-tag);
  font-size: 11px;
  font-weight: 600;
}

.log-approver {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 13px;
  color: $color-text-title;
  font-weight: 500;
  margin-left: auto;

  .el-icon {
    font-size: 13px;
    color: #94A3B8;
  }
}

.log-opinion {
  margin-top: 8px;
  font-size: 13px;
  color: $color-text-body;
  line-height: 1.6;
  padding: 8px 12px;
  background: #F8FAFC;
  border-radius: 6px;
  white-space: pre-wrap;
}

:deep(.el-timeline-item__tail) {
  border-left-color: #E2E8F0;
}

:deep(.el-timeline-item__timestamp) {
  font-size: 12px;
  color: #94A3B8;
}

// ── 操作栏（sticky 底部）─────────────────────────────────────────
.action-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 16px 24px;
  background: #fff;
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: 0 -2px 8px rgba(0, 0, 0, 0.04);
  position: sticky;
  bottom: 16px;
  flex-wrap: wrap;
}

.action-right {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
  align-items: center;
}

.btn-edit {
  border-color: $color-primary;
  color: $color-primary;
  background: var(--theme-bg-soft);

  &:hover {
    background: var(--theme-bg-lighter);
    border-color: $color-primary-dark;
    color: $color-primary-dark;
  }
}

.btn-files {
  border-color: $color-primary;
  color: $color-primary;
  background: var(--theme-bg-soft);

  &:hover {
    background: var(--theme-bg-lighter);
    border-color: $color-primary-dark;
    color: $color-primary-dark;
  }
}

.btn-print {
  border-color: #CBD5E1;
  color: $color-text-body;

  &:hover {
    border-color: $color-primary;
    color: $color-primary;
    background: var(--theme-bg-soft);
  }
}

.el-button {
  border-radius: var(--radius-btn);
  font-weight: 500;
}
</style>
