// lkda-web-react/src/views/borrow/BorrowApproveView.tsx
import { useState, useMemo } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from '@tanstack/react-table'
import {
  Search,
  RefreshCw,
  SlidersHorizontal,
  PenSquare,
  CheckCircle2,
  XCircle,
  User,
  Building,
  Phone,
} from 'lucide-react'

import PageHeader from '@/components/PageHeader'
import ViewModeToggle from '@/components/ViewModeToggle'
import { useViewMode } from '@/hooks/useViewMode'
import { Button } from '@/components/ui/button'
import {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
} from '@/components/ui/tooltip'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select'
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerBody,
  DrawerFooter,
  DrawerCloseButton,
} from '@/components/ui/drawer'
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@/components/ui/table'
import Pagination from '@/components/ui/pagination'
import EmptyState from '@/components/EmptyState'
import StatusTag from '@/components/StatusTag'
import { BorrowApi, type BorrowQueryDTO } from '@/api/borrow'
import type { BorrowVO } from '@/types/vo'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'

/* ── 常量 ───────────────────────────────────────────────────── */
const PAGE_SIZE = 20

const STATUS_OPTIONS = [
  { label: '全部状态', value: '_all' },
  { label: '待审批', value: '0' },
  { label: '已借出', value: '1' },
  { label: '已驳回', value: '2' },
  { label: '已归还', value: '3' },
  { label: '逾期', value: '4' },
]

/* ── 页面组件 ───────────────────────────────────────────────── */
export default function BorrowApproveView() {
  const queryClient = useQueryClient()
  const [query, setQuery] = useState<BorrowQueryDTO>({
    current: 1,
    size: PAGE_SIZE,
  })
  const [filterOpen, setFilterOpen] = useState(false)
  const [viewMode, setViewMode] = useViewMode('lkda_borrow_approve_view')

  /* ── 审批Drawer状态 ───────────────────────────────────────── */
  const [selected, setSelected] = useState<BorrowVO | null>(null)
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [opinion, setOpinion] = useState('')

  /* ── 数据查询 ─────────────────────────────────────────────── */
  const { data: pageData, isLoading } = useQuery({
    queryKey: ['borrow', 'pending', query],
    queryFn: () => BorrowApi.pendingList(query),
  })

  const records = pageData?.records ?? []
  const totalPages = Math.ceil((pageData?.total ?? 0) / PAGE_SIZE)

  /* ── 通过Mutation ─────────────────────────────────────────── */
  const passMutation = useMutation({
    mutationFn: ({ borrowId, opinion }: { borrowId: number; opinion?: string }) =>
      BorrowApi.approve(borrowId, undefined, opinion),
    onSuccess: () => {
      toast.success('审批已通过')
      setDrawerOpen(false)
      setSelected(null)
      setOpinion('')
      queryClient.invalidateQueries({ queryKey: ['borrow', 'pending'] })
      queryClient.invalidateQueries({ queryKey: ['borrow', 'history'] })
      queryClient.invalidateQueries({ queryKey: ['borrow', 'my'] })
      queryClient.invalidateQueries({ queryKey: ['volume'] })
    },
  })

  /* ── 驳回Mutation ─────────────────────────────────────────── */
  const rejectMutation = useMutation({
    mutationFn: ({ borrowId, opinion }: { borrowId: number; opinion: string }) =>
      BorrowApi.reject(borrowId, opinion),
    onSuccess: () => {
      toast.success('审批已驳回')
      setDrawerOpen(false)
      setSelected(null)
      setOpinion('')
      queryClient.invalidateQueries({ queryKey: ['borrow', 'pending'] })
      queryClient.invalidateQueries({ queryKey: ['borrow', 'history'] })
      queryClient.invalidateQueries({ queryKey: ['borrow', 'my'] })
      queryClient.invalidateQueries({ queryKey: ['volume'] })
    },
  })

  function handlePass() {
    if (!selected) return
    passMutation.mutate({
      borrowId: selected.borrowId,
      opinion: opinion.trim() || undefined,
    })
  }

  function handleReject() {
    if (!selected) return
    if (!opinion.trim()) {
      toast.error('驳回时必须填写审批意见')
      return
    }
    rejectMutation.mutate({
      borrowId: selected.borrowId,
      opinion: opinion.trim(),
    })
  }

  function openDrawer(borrow: BorrowVO) {
    setSelected(borrow)
    setOpinion('')
    setDrawerOpen(true)
  }

  /* ── 表格 ─────────────────────────────────────────────────── */
  const columnHelper = createColumnHelper<BorrowVO>()

  const columns = useMemo(
    () => [
      columnHelper.accessor('archiveNo', {
        header: '档号',
        cell: (info) => (
          <span className="font-mono text-xs text-slate-body">
            {info.getValue()}
          </span>
        ),
      }),
      columnHelper.accessor('volumeTitle', {
        header: '档案名称',
        cell: (info) => (
          <span className="font-medium text-slate-title max-w-[180px] truncate block">
            {info.getValue()}
          </span>
        ),
      }),
      columnHelper.accessor('borrowerName', {
        header: '申请人',
        cell: (info) => (
          <span className="whitespace-nowrap text-sm text-slate-body">{info.getValue() || '—'}</span>
        ),
      }),
      columnHelper.accessor('borrowerDept', {
        header: '部门',
        cell: (info) => (
          <span className="text-sm text-slate-body">{info.getValue() || '—'}</span>
        ),
      }),
      columnHelper.accessor('applyCount', {
        header: '份数',
        cell: (info) => <span className="whitespace-nowrap">{info.getValue()} 份</span>,
      }),
      columnHelper.accessor('status', {
        header: '状态',
        cell: (info) => (
          <span className="whitespace-nowrap">
            <StatusTag
              type="borrow"
              value={info.getValue()}
              remainDays={info.row.original.remainingDays ?? undefined}
            />
          </span>
        ),
      }),
      columnHelper.accessor('createdAt', {
        header: '申请时间',
        cell: (info) => {
          const val = info.getValue()
          return <span className="whitespace-nowrap">{val ? val.slice(0, 16).replace('T', ' ') : '—'}</span>
        },
      }),
      columnHelper.display({
        id: 'actions',
        header: '操作',
        cell: ({ row }) => (
          <TooltipProvider delayDuration={300}>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-7 w-7 text-primary-dark hover:bg-primary/10"
                  onClick={() => openDrawer(row.original)}
                >
                  <PenSquare size={14} />
                </Button>
              </TooltipTrigger>
              <TooltipContent>审批</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        ),
      }),
    ],
    []
  )

  const table = useReactTable({
    data: records,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })

  /* ── 筛选事件 ─────────────────────────────────────────────── */
  function handleSearch() {
    setQuery((prev) => ({ ...prev, current: 1 }))
  }

  function handleReset() {
    setQuery({
      current: 1,
      size: PAGE_SIZE,
    })
  }

  /* ── 筛选表单 ─────────────────────────────────────────────── */
  const filterForm = (
    <div className="space-y-4 md:flex md:items-center md:gap-2 md:space-y-0">
      <div className="md:w-[120px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">借阅状态</label>
        <Select
          value={query.status?.toString() ?? '_all'}
          onValueChange={(v) =>
            setQuery((prev) => ({
              ...prev,
              status: v === '_all' ? undefined : Number(v),
              current: 1,
            }))
          }
        >
          <SelectTrigger>
            <SelectValue placeholder="借阅状态" />
          </SelectTrigger>
          <SelectContent>
            {STATUS_OPTIONS.map((s) => (
              <SelectItem key={s.value} value={s.value}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="md:w-[240px]">
        <label className="mb-1.5 block text-sm font-medium text-slate-body md:hidden">关键词</label>
        <Input
          placeholder="档号 / 档案名称 / 申请人"
          value={query.keyword ?? ''}
          onChange={(e) =>
            setQuery((prev) => ({ ...prev, keyword: e.target.value, current: 1 }))
          }
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
        />
      </div>
    </div>
  )

  return (
    <div>
      {/* ── 电脑端：标题 + 检索区合并 ──────────────────────────── */}
      <div className="mb-3 hidden md:block">
        <div className="mb-2 flex items-center gap-2">
          <PenSquare size={20} className="text-primary-dark" />
          <h2 className="text-xl font-bold text-slate-title">借阅审批</h2>
          <ViewModeToggle value={viewMode} onChange={setViewMode} className="ml-auto" />
        </div>
        <div className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] px-4 py-2.5">
          <div className="flex items-center gap-2">
            <div className="flex-1 min-w-0">{filterForm}</div>
            <div className="flex shrink-0 gap-2">
              <Button onClick={handleSearch}>
                <Search size={16} />
                检索
              </Button>
              <Button variant="outline" onClick={handleReset}>
                <RefreshCw size={16} />
                重置
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* ── 手机端标题 ─────────────────────────────────────────── */}
      <PageHeader
        title={<span className="flex items-center gap-2"><PenSquare size={22} className="text-primary-dark" />借阅审批</span>}
        className="md:hidden"
      />

      {/* ── 手机端检索栏 ───────────────────────────────────────── */}
      <div className="mb-4 flex gap-2 md:hidden">
        <Input
          placeholder="档号 / 档案名称 / 申请人"
          value={query.keyword ?? ''}
          onChange={(e) =>
            setQuery((prev) => ({ ...prev, keyword: e.target.value, current: 1 }))
          }
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="flex-1"
        />
        <Button variant="outline" onClick={() => setFilterOpen(true)}>
          <SlidersHorizontal size={16} />
          筛选
        </Button>
      </div>

      {/* ── 内容区 ─────────────────────────────────────────────── */}
      <div className="overflow-hidden rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)]">
        {/* 统计栏 */}
        <div className="flex items-center justify-between border-b border-[var(--color-border-light)] px-5 py-3">
          <span className="text-sm text-slate-body">
            共 <strong className="text-primary-dark">{pageData?.total ?? 0}</strong> 条记录
          </span>
        </div>

        {/* 电脑端表格视图 */}
        <div className={cn('overflow-auto', viewMode === 'table' ? 'hidden md:block' : 'hidden')}>
          {isLoading ? (
            <div className="space-y-3 p-8">
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="h-10 animate-pulse rounded bg-[var(--color-bg-soft)]" />
              ))}
            </div>
          ) : records.length === 0 ? (
            <div className="py-12">
              <EmptyState description="暂无待审批的借阅申请" />
            </div>
          ) : (
            <Table>
              <TableHeader>
                {table.getHeaderGroups().map((hg) => (
                  <tr key={hg.id}>
                    {hg.headers.map((h) => (
                      <TableHead key={h.id}>
                        {h.isPlaceholder
                          ? null
                          : flexRender(h.column.columnDef.header, h.getContext())}
                      </TableHead>
                    ))}
                  </tr>
                ))}
              </TableHeader>
              <TableBody>
                {table.getRowModel().rows.map((row) => (
                  <TableRow key={row.id}>
                    {row.getVisibleCells().map((cell) => (
                      <TableCell key={cell.id}>
                        {flexRender(cell.column.columnDef.cell, cell.getContext())}
                      </TableCell>
                    ))}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </div>

        {/* 手机端卡片列表 */}
        <div className={cn('grid grid-cols-1 gap-3 p-3', viewMode === 'card' ? 'md:grid-cols-2 lg:grid-cols-3' : 'md:hidden')}>
          {isLoading
            ? Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="h-44 animate-pulse rounded-card bg-[var(--color-bg-soft)]" />
              ))
            : records.length === 0
              ? <EmptyState description="暂无待审批的借阅申请" />
              : records.map((borrow) => (
                  <div
                    key={borrow.borrowId}
                    className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-main)] p-4 shadow-card active:scale-[0.99] transition-transform"
                  >
                    <div className="mb-2 flex items-start justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <div className="mb-0.5 font-mono text-[11px] text-[var(--text-faint)] truncate">
                          {borrow.archiveNo}
                        </div>
                        <div className="text-sm font-semibold text-slate-title line-clamp-2">
                          {borrow.volumeTitle}
                        </div>
                      </div>
                      <StatusTag
                        type="borrow"
                        value={borrow.status}
                        remainDays={borrow.remainingDays ?? undefined}
                      />
                    </div>

                    <div className="mb-3 grid grid-cols-2 gap-x-4 gap-y-1.5 text-xs text-slate-body">
                      <div className="flex justify-between">
                        <span className="text-[var(--text-faint)]">申请人</span>
                        <span>{borrow.borrowerName || '—'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-[var(--text-faint)]">部门</span>
                        <span className="truncate text-right">{borrow.borrowerDept || '—'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-[var(--text-faint)]">申请份数</span>
                        <span>{borrow.applyCount} 份</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-[var(--text-faint)]">申请时间</span>
                        <span>{borrow.createdAt?.slice(0, 16).replace('T', ' ') || '—'}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 border-t border-[var(--color-border-light)] pt-2.5">
                      <Button
                        size="sm"
                        className="flex-1 h-8 text-xs"
                        onClick={() => openDrawer(borrow)}
                      >
                        <PenSquare size={13} className="mr-1" />
                        审批
                      </Button>
                    </div>
                  </div>
                ))}
        </div>

        {/* 分页 */}
        {totalPages > 1 && (
          <div className="border-t border-[var(--color-border-light)] px-5 py-4">
            <Pagination
              current={query.current ?? 1}
              total={totalPages}
              onChange={(p) => setQuery((prev) => ({ ...prev, current: p }))}
            />
          </div>
        )}
      </div>

      {/* ── 手机端筛选 Drawer ──────────────────────────────────── */}
      <Drawer open={filterOpen} onOpenChange={setFilterOpen}>
        <DrawerContent>
          <DrawerHeader>
            <DrawerTitle>筛选条件</DrawerTitle>
            <DrawerCloseButton />
          </DrawerHeader>
          <DrawerBody>{filterForm}</DrawerBody>
          <DrawerFooter>
            <Button variant="outline" onClick={handleReset}>
              <RefreshCw size={16} className="mr-1.5" />
              重置
            </Button>
            <Button
              onClick={() => {
                handleSearch()
                setFilterOpen(false)
              }}
            >
              <Search size={16} className="mr-1.5" />
              检索
            </Button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>

      {/* ── 审批 Drawer ─────────────────────────────────────────── */}
      <Drawer open={drawerOpen} onOpenChange={setDrawerOpen}>
        <DrawerContent>
          <DrawerHeader>
            <DrawerTitle className="flex items-center gap-2">
              <PenSquare size={20} className="text-primary-dark" />
              借阅审批
            </DrawerTitle>
            <DrawerCloseButton />
          </DrawerHeader>

          <DrawerBody className="space-y-5">
            {selected && (
              <>
                {/* 申请人信息 */}
                <div className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-soft)] p-4">
                  <h4 className="mb-3 text-sm font-semibold text-slate-title">申请人信息</h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex items-center gap-2 text-slate-body">
                      <User size={14} className="text-[var(--text-faint)]" />
                      <span>{selected.borrowerName || '—'}</span>
                    </div>
                    <div className="flex items-center gap-2 text-slate-body">
                      <Building size={14} className="text-[var(--text-faint)]" />
                      <span>{selected.borrowerDept || '—'}</span>
                    </div>
                    {selected.borrowerPhone && (
                      <div className="flex items-center gap-2 text-slate-body">
                        <Phone size={14} className="text-[var(--text-faint)]" />
                        <span>{selected.borrowerPhone}</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* 档案信息 */}
                <div className="rounded-card border border-[var(--color-border-light)] bg-[var(--color-bg-soft)] p-4">
                  <h4 className="mb-3 text-sm font-semibold text-slate-title">档案信息</h4>
                  <div className="mb-2 font-mono text-xs font-semibold text-primary-dark">
                    {selected.archiveNo}
                  </div>
                  <div className="mb-3 text-sm font-medium text-slate-title">
                    {selected.volumeTitle}
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs text-slate-body">
                    <div>申请份数：{selected.applyCount} 份</div>
                    <div>计划归还：{selected.planReturnDate?.slice(0, 10) || '—'}</div>
                  </div>
                </div>

                {/* 借阅原因 */}
                {selected.reason && (
                  <div>
                    <h4 className="mb-2 text-sm font-semibold text-slate-title">借阅原因</h4>
                    <p className="rounded-lg bg-[var(--color-bg-soft)] p-3 text-sm leading-relaxed text-slate-body">
                      {selected.reason}
                    </p>
                  </div>
                )}

                {/* 审批意见 */}
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-slate-title">
                    审批意见
                    <span className="ml-1 text-xs font-normal text-[var(--text-faint)]">（驳回时必填）</span>
                  </label>
                  <textarea
                    value={opinion}
                    onChange={(e) => setOpinion(e.target.value)}
                    placeholder="请填写审批意见..."
                    rows={3}
                    className={cn(
                      'w-full resize-none rounded-btn border border-[var(--color-border-light)] bg-[var(--color-bg-main)] px-3 py-2.5 text-sm text-[var(--color-slate-title)] placeholder:text-[var(--text-faint)] focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary'
                    )}
                  />
                </div>
              </>
            )}
          </DrawerBody>

          <DrawerFooter className="max-md:flex-row max-md:justify-stretch">
            <Button
              variant="outline"
              className="max-md:flex-1 text-slate-body"
              onClick={handleReject}
              disabled={passMutation.isPending || rejectMutation.isPending}
            >
              <XCircle size={16} className="mr-1.5" />
              驳回
            </Button>
            <Button
              className="max-md:flex-1"
              loading={passMutation.isPending || rejectMutation.isPending}
              onClick={handlePass}
            >
              <CheckCircle2 size={16} className="mr-1.5" />
              批准
            </Button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </div>
  )
}

// lkda-web/src/views/borrow/BorrowApproveView.vue
<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { BorrowApi } from '@/api/borrow'
import type { BorrowVO } from '@/types/vo'
import ViewModeToggle from '@/components/ViewModeToggle.vue'
import { useViewMode } from '@/composables/useViewMode'

// ── 视图模式 ─────────────────────────────────────────────────────
const viewMode = useViewMode('borrow_approve')

// ── 查询参数 ─────────────────────────────────────────────────────
const query = reactive({
  keyword: '',
  current: 1,
  size:    20,
})

// ── 列表数据 ─────────────────────────────────────────────────────
const loading   = ref(false)
const tableData = ref<BorrowVO[]>([])
const total     = ref(0)

async function loadList() {
  loading.value = true
  try {
    const res = await BorrowApi.approvePage({
      keyword: query.keyword || undefined,
      current: query.current,
      size:    query.size,
    })
    tableData.value = res.records
    total.value     = res.total
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  query.current = 1
  loadList()
}

function handleReset() {
  query.keyword = ''
  query.current = 1
  loadList()
}

onMounted(loadList)

// ── Drawer 状态 ──────────────────────────────────────────────────
const drawerVisible = ref(false)
const currentRow    = ref<BorrowVO | null>(null)
const opinion       = ref('')
const submitting    = ref(false)

function openApprove(row: BorrowVO) {
  currentRow.value    = row
  opinion.value       = ''
  drawerVisible.value = true
}

const drawerTitle = computed(() =>
  currentRow.value ? `审批 · ${currentRow.value.archiveNo}` : '借阅审批',
)

// ── 可借份数超出警告 ─────────────────────────────────────────────
const isOverApply = computed(() => {
  if (!currentRow.value) return false
  const avail = currentRow.value.volumeAvailable
  if (avail === undefined) return false
  return currentRow.value.applyCount > avail
})

// ── 审批操作 ─────────────────────────────────────────────────────
function validateOpinion(): boolean {
  if (!opinion.value.trim()) {
    ElMessage.warning('请填写审批意见')
    return false
  }
  return true
}

async function handleApprove() {
  if (!validateOpinion() || !currentRow.value) return

  await ElMessageBox.confirm(
    `确认批准「${currentRow.value.borrowerName}」对档案「${currentRow.value.archiveNo}」的借阅申请？\n批准后档案在库状态将更新为"借出"。`,
    '确认批准',
    {
      type:                'success',
      confirmButtonText:   '确认批准',
      cancelButtonText:    '取消',
    },
  )

  submitting.value = true
  try {
    await BorrowApi.approve(currentRow.value.borrowId, { action: 'PASS', opinion: opinion.value.trim() })
    ElMessage.success('已批准，档案在库状态已更新')
    drawerVisible.value = false
    loadList()
  } finally {
    submitting.value = false
  }
}

async function handleReject() {
  if (!validateOpinion() || !currentRow.value) return

  await ElMessageBox.confirm(
    `确认驳回「${currentRow.value.borrowerName}」的借阅申请？`,
    '确认驳回',
    {
      type:                'warning',
      confirmButtonText:   '确认驳回',
      cancelButtonText:    '取消',
    },
  )

  submitting.value = true
  try {
    await BorrowApi.reject(currentRow.value.borrowId, { action: 'REJECT', opinion: opinion.value.trim() })
    ElMessage.success('已驳回该借阅申请')
    drawerVisible.value = false
    loadList()
  } finally {
    submitting.value = false
  }
}

// ── 分页 ─────────────────────────────────────────────────────────
function handlePageChange(page: number) {
  query.current = page
  loadList()
}
function handleSizeChange(size: number) {
  query.size    = size
  query.current = 1
  loadList()
}
</script>

<template>
  <div class="page-container">
    <!-- ── 页头 ───────────────────────────────────────────────── -->
    <PageHeader
      title="借阅审批队列"
      :breadcrumbs="[{ label: '借阅管理' }, { label: '借阅审批队列' }]"
    />

    <!-- ── 筛选栏 ─────────────────────────────────────────────── -->
    <el-card class="filter-card" shadow="never">
      <div class="filter-row">
        <el-input
          v-model="query.keyword"
          placeholder="搜索申请人姓名或档号"
          clearable
          class="filter-keyword"
          @keyup.enter="handleSearch"
          @clear="handleSearch"
        >
          <template #prefix><el-icon><Search /></el-icon></template>
        </el-input>
        <el-button type="primary" @click="handleSearch">
          <el-icon><Search /></el-icon>
          查询
        </el-button>
        <el-button @click="handleReset">
          <el-icon><Refresh /></el-icon>
          重置
        </el-button>
      </div>
    </el-card>

    <!-- ── 数据表格 ───────────────────────────────────────────── -->
    <el-card class="table-card" shadow="never">
      <div class="table-toolbar">
        <span class="queue-badge">待审批</span>
        <span class="queue-count">
          共 <strong>{{ total }}</strong> 条待处理借阅申请
        </span>
        <div class="toolbar-spacer" />
        <ViewModeToggle v-model="viewMode" />
      </div>

      <template v-if="loading && tableData.length === 0">
        <el-skeleton :rows="8" animated class="skeleton-padding" />
      </template>

      <EmptyState
        v-else-if="!loading && tableData.length === 0"
        description="暂无待审批的借阅申请"
      />

      <el-table
        v-else-if="viewMode === 'table'"
        v-loading="loading"
        :data="tableData"
        row-key="borrowId"
        class="approve-table"
        max-height="calc(100vh - 300px)"
      >
        <el-table-column label="档号" min-width="165" fixed>
          <template #default="{ row }">
            <span class="archive-no">{{ row.archiveNo }}</span>
          </template>
        </el-table-column>

        <el-table-column label="档案题名" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <span class="title-cell">{{ row.volumeTitle }}</span>
          </template>
        </el-table-column>

        <el-table-column label="申请人" width="120">
          <template #default="{ row }">
            <div class="applicant-cell">
              <span class="applicant-name">{{ row.borrowerName }}</span>
              <span class="applicant-dept">{{ row.borrowerDept }}</span>
            </div>
          </template>
        </el-table-column>

        <el-table-column label="份数" width="72" align="center">
          <template #default="{ row }">
            <span class="count-cell">{{ row.applyCount }} 件</span>
          </template>
        </el-table-column>

        <el-table-column label="申请时间" min-width="155">
          <template #default="{ row }">
            <span class="time-cell">{{ row.createdAt }}</span>
          </template>
        </el-table-column>

        <el-table-column label="计划归还" width="112">
          <template #default="{ row }">
            <span class="time-cell">{{ row.planReturnDate || '—' }}</span>
          </template>
        </el-table-column>

        <el-table-column label="操作" width="100" fixed="right" align="center">
          <template #default="{ row }">
            <el-button
              type="primary"
              size="small"
              class="btn-approve"
              @click="openApprove(row)"
            >
              <el-icon><EditPen /></el-icon>
              审批
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <!-- 卡片视图 -->
      <div v-else v-loading="loading" class="card-grid-wrap">
        <div class="card-grid">
          <div
            v-for="row in tableData"
            :key="row.borrowId"
            class="archive-card"
            @click="openApprove(row)"
          >
            <div class="archive-card-icon-wrap">
              <el-icon class="archive-card-icon"><Suitcase /></el-icon>
            </div>
            <div class="archive-card-body">
              <div class="archive-card-no">{{ row.archiveNo }}</div>
              <div class="archive-card-title" :title="row.volumeTitle">
                {{ row.volumeTitle }}
              </div>
              <div class="archive-card-meta">
                <span class="applicant-name">{{ row.borrowerName }}</span>
                <span class="applicant-dept">{{ row.borrowerDept }}</span>
              </div>
              <div class="archive-card-meta">
                <span class="meta-text">{{ row.applyCount }} 件</span>
                <span class="meta-text">计划归还 {{ row.planReturnDate || '—' }}</span>
              </div>
            </div>
            <div class="archive-card-footer">
              <span class="meta-text">{{ row.createdAt }}</span>
              <el-button
                type="primary"
                size="small"
                class="btn-approve"
                @click.stop="openApprove(row)"
              >
                <el-icon><EditPen /></el-icon>
                审批
              </el-button>
            </div>
          </div>
        </div>
      </div>

      <div v-if="total > 0" class="pagination-wrap">
        <el-pagination
          v-model:current-page="query.current"
          v-model:page-size="query.size"
          :total="total"
          :page-sizes="[20, 50, 100]"
          layout="total, sizes, prev, pager, next, jumper"
          background
          @current-change="handlePageChange"
          @size-change="handleSizeChange"
        />
      </div>
    </el-card>

    <!-- ─────────────────────────────────────────────────────────── -->
    <!-- 审批侧滑 Drawer                                             -->
    <!-- ─────────────────────────────────────────────────────────── -->
    <el-drawer
      v-model="drawerVisible"
      :title="drawerTitle"
      direction="rtl"
      size="580px"
      :destroy-on-close="false"
      class="approve-drawer"
    >
      <template #header>
        <div class="drawer-header">
          <div class="drawer-title-row">
            <span class="drawer-title-icon">
              <el-icon><Suitcase /></el-icon>
            </span>
            <span class="drawer-title-text">{{ drawerTitle }}</span>
          </div>
          <span v-if="currentRow" class="drawer-sub">
            {{ currentRow.volumeTitle }}
          </span>
        </div>
      </template>

      <div v-if="currentRow" class="drawer-body">

        <!-- ── 申请人信息 ──────────────────────────────────────── -->
        <section class="detail-section">
          <div class="section-header">
            <span class="section-bar" />
            <span class="section-title">申请人信息</span>
          </div>
          <div class="applicant-card">
            <div class="applicant-avatar">
              {{ currentRow.borrowerName.slice(-1) }}
            </div>
            <div class="applicant-info">
              <span class="applicant-info-name">{{ currentRow.borrowerName }}</span>
              <span class="applicant-info-dept">{{ currentRow.borrowerDept }}</span>
              <span v-if="currentRow.borrowerPhone" class="applicant-info-phone">
                <el-icon><Phone /></el-icon>
                {{ currentRow.borrowerPhone }}
              </span>
            </div>
          </div>
        </section>

        <!-- ── 档案信息 ────────────────────────────────────────── -->
        <section class="detail-section">
          <div class="section-header">
            <span class="section-bar" />
            <span class="section-title">档案信息</span>
          </div>
          <div class="archive-banner">
            <el-icon class="banner-icon"><DocumentChecked /></el-icon>
            <span class="banner-no">{{ currentRow.archiveNo }}</span>
          </div>
          <div class="detail-block">
            <div class="detail-row">
              <span class="dl">档案题名</span>
              <span class="dv">{{ currentRow.volumeTitle }}</span>
            </div>
            <div v-if="currentRow.volumeAvailable !== undefined" class="detail-row">
              <span class="dl">剩余可借</span>
              <span
                class="dv available-val"
                :class="{
                  'is-ok':    currentRow.volumeAvailable > 0 && !isOverApply,
                  'is-warn':  isOverApply,
                  'is-empty': currentRow.volumeAvailable === 0,
                }"
              >
                <el-icon v-if="currentRow.volumeAvailable === 0"><CircleClose /></el-icon>
                <el-icon v-else-if="isOverApply"><Warning /></el-icon>
                <el-icon v-else><CircleCheck /></el-icon>
                {{
                  currentRow.volumeAvailable === 0
                    ? '已借空（无法批准）'
                    : `${currentRow.volumeAvailable} 件可借（共 ${currentRow.volumeCopies ?? '?'} 件）`
                }}
              </span>
            </div>
            <div v-if="isOverApply" class="over-apply-warn">
              <el-icon><WarningFilled /></el-icon>
              申请份数（{{ currentRow.applyCount }} 件）超出剩余可借份数，请核实后再批准
            </div>
          </div>
        </section>

        <!-- ── 借阅申请详情 ────────────────────────────────────── -->
        <section class="detail-section">
          <div class="section-header">
            <span class="section-bar" />
            <span class="section-title">借阅申请详情</span>
          </div>
          <div class="detail-block">
            <div class="detail-row">
              <span class="dl">申请份数</span>
              <span class="dv dv--emphasis">{{ currentRow.applyCount }} 件</span>
            </div>
            <div class="detail-row">
              <span class="dl">计划归还</span>
              <span class="dv">{{ currentRow.planReturnDate || '—' }}</span>
            </div>
            <div class="detail-row">
              <span class="dl">申请时间</span>
              <span class="dv">{{ currentRow.createdAt }}</span>
            </div>
          </div>
        </section>

        <!-- ── 借阅原因 ────────────────────────────────────────── -->
        <section class="detail-section">
          <div class="section-header">
            <span class="section-bar" />
            <span class="section-title">借阅原因</span>
          </div>
          <div class="reason-block">
            {{ currentRow.reason || '（申请人未填写借阅原因）' }}
          </div>
        </section>

      </div>

      <!-- ── 审批操作区（固定底部）──────────────────────────────── -->
      <template #footer>
        <div class="approve-action-bar">
          <div class="opinion-wrap">
            <label class="opinion-label">
              审批意见
              <span class="required-star">*</span>
            </label>
            <el-input
              v-model="opinion"
              type="textarea"
              :rows="3"
              placeholder="请填写审批意见（必填）"
              maxlength="500"
              show-word-limit
              class="opinion-textarea"
            />
          </div>
          <div class="action-btns">
            <el-button
              size="large"
              class="btn-reject"
              :loading="submitting"
              @click="handleReject"
            >
              <el-icon><CircleClose /></el-icon>
              驳回
            </el-button>
            <el-button
              type="primary"
              size="large"
              class="btn-pass"
              :loading="submitting"
              :disabled="currentRow?.volumeAvailable === 0"
              @click="handleApprove"
            >
              <el-icon><CircleCheck /></el-icon>
              批准
            </el-button>
          </div>
          <p
            v-if="currentRow?.volumeAvailable === 0"
            class="empty-stock-tip"
          >
            <el-icon><WarningFilled /></el-icon>
            该档案当前无可借份数，无法批准，请驳回并通知申请人等待归还
          </p>
        </div>
      </template>
    </el-drawer>
  </div>
</template>

<style scoped lang="scss">
.page-container {
  padding: 16px 24px 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

// ── 筛选栏 ────────────────────────────────────────────────────────
.filter-card {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: var(--shadow-card);

  :deep(.el-card__body) { padding: 12px 20px; }
}

.filter-row {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}

.filter-keyword { flex: 1; min-width: 240px; max-width: 400px; }

@media (max-width: 768px) {
  .filter-keyword { width: 100%; max-width: none; flex: none; }
}

// ── 表格卡片 ──────────────────────────────────────────────────────
.table-card {
  border-radius: var(--radius-card);
  border: 1px solid #E2E8F0;
  box-shadow: var(--shadow-card);

  :deep(.el-card__body) { padding: 0; }
}

.skeleton-padding { padding: 24px; }

.table-toolbar {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 20px 8px;
  border-bottom: 1px solid #F1F5F9;
}

.queue-badge {
  display: inline-flex;
  align-items: center;
  padding: 3px 12px;
  border-radius: var(--radius-tag);
  font-size: 12px;
  font-weight: 600;
  background: #F1F5F9;
  color: #64748B;
}

.queue-count {
  font-size: 13px;
  color: $color-text-body;

  strong { color: $color-primary-dark; font-weight: 700; }
}

.approve-table {
  width: 100%;

  :deep(.el-table__row:hover > td) { background: var(--theme-bg-light) !important; }

  :deep(th.el-table__cell) {
    background: var(--theme-bg-card);
    color: $color-text-body;
    font-weight: 600;
    font-size: 13px;
    border-bottom: 2px solid #E2E8F0;
  }

  :deep(.el-table__cell) { padding: 11px 8px; }
}

.archive-no {
  font-family: 'JetBrains Mono', Consolas, monospace;
  font-size: 12px;
  font-weight: 600;
  color: $color-primary-dark;
}

.title-cell {
  font-size: 13px;
  color: $color-text-title;
  font-weight: 500;
}

.applicant-cell {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.applicant-name {
  font-size: 13px;
  color: $color-text-title;
  font-weight: 500;
}

.applicant-dept {
  font-size: 11px;
  color: #94A3B8;
}

.count-cell {
  font-size: 13px;
  font-weight: 600;
  color: $color-text-title;
}

.time-cell {
  font-size: 12px;
  color: $color-text-body;
}

.btn-approve {
  background: $color-primary;
  border-color: $color-primary;
  border-radius: var(--radius-btn);
  font-weight: 500;
  font-size: 12px;

  &:hover {
    background: $color-primary-dark;
    border-color: $color-primary-dark;
    transform: translateY(-1px);
  }
}

.pagination-wrap {
  display: flex;
  justify-content: flex-end;
  padding: 14px 20px;
  border-top: 1px solid #F1F5F9;

  :deep(.el-pagination.is-background .el-pager li.is-active) {
    background: $color-primary;
    border-color: $color-primary;
  }
}

.toolbar-spacer { flex: 1; }

// ── 卡片视图 ──────────────────────────────────────────────────────
.card-grid-wrap {
  padding: 16px 20px;
  min-height: 200px;
}

.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 12px;
}

.archive-card {
  background: #fff;
  border: 1px solid #E2E8F0;
  border-radius: var(--radius-card);
  padding: 16px;
  cursor: pointer;
  transition: border-color 0.2s, box-shadow 0.2s, transform 0.2s;
  display: flex;
  flex-direction: column;
  gap: 12px;

  &:hover {
    border-color: $color-primary;
    box-shadow: 0 4px 16px color-mix(in srgb, var(--color-primary) 15%, transparent);
    transform: translateY(-2px);
  }
}

.archive-card-icon-wrap {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  background: linear-gradient(135deg, var(--theme-bg-lighter), var(--theme-border-medium));
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.archive-card-icon {
  font-size: 22px;
  color: $color-primary-dark;
}

.archive-card-body {
  flex: 1;
  min-width: 0;
}

.archive-card-no {
  font-size: 11px;
  color: #94A3B8;
  margin-bottom: 4px;
  font-family: monospace;
  letter-spacing: 0.3px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.archive-card-title {
  font-size: 14px;
  font-weight: 600;
  color: $color-text-title;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  margin-bottom: 8px;
}

.archive-card-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 4px;
}

.meta-text {
  font-size: 12px;
  color: $color-text-body;
}

.archive-card-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
  padding-top: 10px;
  border-top: 1px solid #F1F5F9;
  flex-wrap: wrap;
}

// ── Drawer ────────────────────────────────────────────────────────
.approve-drawer {
  :deep(.el-drawer__header) {
    padding: 0;
    margin-bottom: 0;
    border-bottom: 1px solid #F1F5F9;
  }
  :deep(.el-drawer__body)  { padding: 0; overflow-y: auto; }
  :deep(.el-drawer__footer){ padding: 0; border-top: 1px solid #E2E8F0; }
}

.drawer-header {
  padding: 10px 20px 8px;
  background: linear-gradient(135deg, var(--theme-bg-soft), var(--theme-bg-light));
}

.drawer-title-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.drawer-title-icon {
  width: 30px;
  height: 30px;
  border-radius: 8px;
  background: $color-primary;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 15px;
  flex-shrink: 0;
}

.drawer-title-text {
  font-size: 15px;
  font-weight: 700;
  color: $color-text-title;
  font-family: 'JetBrains Mono', Consolas, monospace;
  letter-spacing: 0.3px;
}

.drawer-sub {
  display: block;
  margin-top: 4px;
  font-size: 12px;
  color: $color-text-body;
  padding-left: 38px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

// ── Drawer 正文 ───────────────────────────────────────────────────
.drawer-body {
  padding: 18px 20px;
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.detail-section { display: flex; flex-direction: column; gap: 10px; }

.section-header {
  display: flex;
  align-items: center;
  gap: 7px;
}

.section-bar {
  width: 3px;
  height: 15px;
  border-radius: 2px;
  background: linear-gradient(180deg, $color-primary, $color-primary-dark);
  flex-shrink: 0;
}

.section-title {
  font-size: 13px;
  font-weight: 600;
  color: $color-text-title;
}

// 申请人卡片
.applicant-card {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 14px 16px;
  background: linear-gradient(135deg, var(--theme-bg-soft), var(--theme-bg-light));
  border-radius: 12px;
  border: 1px solid var(--theme-border-medium);
}

.applicant-avatar {
  width: 42px;
  height: 42px;
  border-radius: 50%;
  background: linear-gradient(135deg, $color-primary, $color-primary-dark);
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  user-select: none;
}

.applicant-info {
  display: flex;
  flex-direction: column;
  gap: 3px;
}

.applicant-info-name {
  font-size: 15px;
  font-weight: 700;
  color: $color-text-title;
}

.applicant-info-dept {
  font-size: 12px;
  color: $color-text-body;
}

.applicant-info-phone {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: #94A3B8;
  font-family: 'JetBrains Mono', Consolas, monospace;

  .el-icon { font-size: 12px; }
}

// 档案横幅
.archive-banner {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 14px;
  background: var(--theme-bg-soft);
  border-radius: 8px;
  border: 1px solid var(--theme-border-medium);
}

.banner-icon { font-size: 18px; color: $color-primary; }

.banner-no {
  font-family: 'JetBrains Mono', Consolas, monospace;
  font-size: 15px;
  font-weight: 700;
  color: $color-primary-dark;
  letter-spacing: 0.5px;
  word-break: break-all;
}

// 字段行
.detail-block {
  background: var(--theme-bg-card);
  border: 1px solid #F1F5F9;
  border-radius: 10px;
  padding: 12px 14px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.detail-row {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}

.dl {
  font-size: 12px;
  color: #94A3B8;
  font-weight: 500;
  white-space: nowrap;
  width: 64px;
  flex-shrink: 0;
  padding-top: 1px;
}

.dv {
  font-size: 13px;
  color: $color-text-title;
  flex: 1;
  word-break: break-all;
  line-height: 1.5;

  &--emphasis {
    font-size: 16px;
    font-weight: 700;
    color: $color-primary-dark;
  }
}

.available-val {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-weight: 600;

  &.is-ok    { color: $color-primary-dark; }
  &.is-warn  { color: #D97706; }
  &.is-empty { color: #DC2626; }

  .el-icon { font-size: 14px; }
}

.over-apply-warn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 10px;
  background: #FFFBEB;
  border: 1px solid #FDE68A;
  border-radius: 6px;
  font-size: 12px;
  color: #92400E;
  font-weight: 500;

  .el-icon { font-size: 13px; color: #D97706; flex-shrink: 0; }
}

.reason-block {
  background: var(--theme-bg-card);
  border: 1px solid #F1F5F9;
  border-radius: 10px;
  padding: 12px 14px;
  font-size: 13px;
  color: $color-text-body;
  line-height: 1.7;
  white-space: pre-wrap;
  min-height: 56px;
}

// 审批操作区
.approve-action-bar {
  padding: 14px 20px 18px;
  background: #fff;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.opinion-wrap { display: flex; flex-direction: column; gap: 6px; }

.opinion-label {
  font-size: 13px;
  font-weight: 600;
  color: $color-text-title;
}

.required-star { color: #EF4444; margin-left: 2px; }

.opinion-textarea {
  width: 100%;

  :deep(.el-textarea__inner) {
    border-radius: 8px;
    font-size: 13px;
    line-height: 1.6;
    resize: vertical;

    &:focus { box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 20%, transparent) !important; }
  }
}

.action-btns {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
}

.btn-reject {
  border-color: #FB923C;
  color: #EA580C;
  background: #FFF7ED;
  border-radius: var(--radius-btn);
  font-weight: 600;
  min-width: 90px;

  &:hover {
    background: #FFEDD5;
    border-color: #EA580C;
    color: #C2410C;
    transform: translateY(-1px);
  }
}

.btn-pass {
  background: $color-primary;
  border-color: $color-primary;
  border-radius: var(--radius-btn);
  font-weight: 600;
  min-width: 90px;

  &:not(:disabled):hover {
    background: $color-primary-dark;
    border-color: $color-primary-dark;
    transform: translateY(-1px);
  }

  &:disabled { opacity: 0.4; }
}

.empty-stock-tip {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: #DC2626;
  margin: 0;

  .el-icon { font-size: 13px; flex-shrink: 0; }
}

.el-button { border-radius: var(--radius-btn); }
</style>
